const translations = {
  'pt-BR': {
    nav: {
      home: 'Home',
      smartCondo: 'Condomínio inteligente',
      solutions: 'Nossas Soluções',
      about: 'Quem Somos',
      contact: 'Contato',
    },
    solutionsSub: {
      access: 'Área de Acesso',
      external: 'Área Externa',
      internal: 'Área Interna',
      facilities: 'Facilities',
      custom: 'Soluções sob medida',
    },
    header: {
      cta: 'Pedir Orçamento',
    },
    hero: {
      slide1: {
        title: 'Câmeras com inteligência<br/>artificial',
        subtitle: 'Com a Now Soluções, seu condomínio conta com câmeras inteligentes que identificam movimentações, acionam sensores e criam barreiras virtuais. Mais precisão, mais proteção, menos preocupações.'
      },
      slide2: {
        title: 'Acesso Inteligente<br/>e Descomplicado',
        subtitle: 'Controle facial, QR Code e reconhecimento veicular. Ofereça segurança e praticidade para moradores e visitantes com a mais alta tecnologia.'
      },
      slide3: {
        title: 'Gestão Completa<br/>na Palma da Mão',
        subtitle: 'Nosso aplicativo centraliza todas as funcionalidades, desde a liberação de visitantes até a reserva de áreas comuns. Gestão eficiente e transparente.'
      },
      cta: 'Fale com um especialista',
    },
    impact: {
      title: 'Nosso Impacto',
      stat1: { value: '+80', label: 'Condomínios atendidos' },
      stat2: { value: '+15', label: 'Anos de Experiência de Mercado' },
      stat3: { value: '+15k', label: 'Moradores Impactados' },
      stat4: { value: '98%', label: 'Satisfação entre síndicos' }
    },
    solutions: {
      title: 'Seu condomínio mais inteligente. Sua vida mais segura.',
      subtitle: 'Combinamos tecnologia de ponta, atendimento próximo e soluções personalizadas para transformar a rotina de condomínios residenciais e comerciais. Cada serviço é desenvolvido para oferecer mais segurança, praticidade e tranquilidade para síndicos, moradores e administradoras.',
      card1: { title: 'Acesso Inteligente', description: 'Controle facial, QR Code, convites digitais, reconhecimento veicular e liberação remota via app.' },
      card2: { title: 'Monitoramento IA', description: 'Câmeras com inteligência artificial, cercas virtuais, alarmes sonoros e sensores com análise de comportamento.' },
      card3: { title: 'Armários Inteligentes', description: 'Recebimento de encomendas 24/7 com segurança e autonomia. Notificações via app para retirada.' },
    },
    about: {
      tagline: 'DIFERENCIAIS',
      title: 'Por que escolher a Now?',
      description: 'Temos a solução inteligente e sob medida para a realidade de cada condomínio. Acompanhamos síndicos e gestores em todas as etapas, desde o diagnóstico até a operação, com suporte dedicado, tecnologia de ponta e foco total em segurança, eficiência e tranquilidade.',
      partnersTagline: 'NOSSOS PARCEIROS',
    },
    cta: {
      title: 'Excelência em cada detalhe',
      description: 'Nosso compromisso é entregar soluções que funcionam de verdade. Com tecnologia de ponta, equipe especializada e suporte contínuo, oferecemos uma experiência de gestão condominial segura, fluida e eficiente.',
      button: 'Fale com um especialista'
    },
    testimonials: {
      title: 'O que nossos clientes dizem',
      t1: { quote: 'Com a Now conseguimos organizar toda a comunicação e controle do nosso condomínio. O aplicativo facilitou muito a vida de todos.', name: 'Carlos Mendes', title: 'síndico', company: 'Condomínio Vila Serena' },
      t2: { quote: 'O sistema de acesso facial e os armários inteligentes mudaram completamente nossa rotina. Estamos mais seguros e organizados.', name: 'Ana Lúcia Barros', title: 'gestora', company: 'Smart Park Alphaville' },
      t3: { quote: 'Suporte técnico ágil e eficiente. A equipe da Now está sempre pronta para nos atender, o que faz toda a diferença na gestão diária.', name: 'Roberto Almeida', title: 'administrador', company: 'Edifício Corporate Tower' },
    },
    footer: {
      description: 'Now Soluções - Conectamos segurança, tecnologia e gestão para transformar seu condomínio.',
      nav: { home: 'Home', about: 'Quem Somos', contact: 'Contato', privacy: 'Política de Privacidade' },
      solutions: { smartCondo: 'Condomínio Inteligente', access: 'Área de Acesso', external: 'Área Externa', internal: 'Área Interna', facilities: 'Facilities', custom: 'Soluções sob Medida' },
      contact: { phone: '(11) 5283-5040', address: 'Rua Antônio Nápoli, 229<br/>Parada São Paulo - SP<br/>02987-030' },
      copyright: '© Now Soluções | Todos os direitos reservados | 2025'
    },
    quemSomos: {
      hero: { title: 'Sobre a Now Soluções', subtitle: 'Conectando tecnologia, segurança e pessoas para criar condomínios mais inteligentes e comunidades mais fortes.' },
      story: { tagline: 'NOSSA JORNADA', title: 'Nascemos para inovar', p1: 'A Now Soluções foi fundada com a missão de revolucionar a gestão condominial no Brasil. Percebemos que a tecnologia poderia ser uma aliada poderosa para síndicos e moradores, trazendo mais segurança, eficiência e tranquilidade para o dia a dia. Desde o início, nosso foco tem sido desenvolver e integrar soluções que realmente fazem a diferença.', p2: 'Com mais de 15 anos de experiência combinada no setor de tecnologia e segurança, nossa equipe se dedica a entender os desafios únicos de cada condomínio, oferecendo um serviço personalizado e um suporte que vai além do esperado.' },
      values: { title: 'Nossos Valores', v1: { title: 'Inovação', description: 'Buscamos constantemente as soluções mais avançadas para garantir a vanguarda tecnológica em segurança e gestão.' }, v2: { title: 'Segurança', description: 'A proteção dos nossos clientes é a nossa prioridade máxima, refletida em cada produto e serviço que oferecemos.' }, v3: { title: 'Foco no Cliente', description: 'Trabalhamos em parceria com síndicos e moradores para entender e atender suas necessidades reais com excelência.' } },
      partners: { title: 'Empresas que confiam em nosso trabalho' }
    },
    contato: {
      hero: { title: 'Fale Conosco', subtitle: 'Tem alguma dúvida ou quer solicitar um orçamento? Nossa equipe está pronta para ajudar.' },
      form: { title: 'Envie uma mensagem', subtitle: 'Preencha o formulário e entraremos em contato o mais breve possível.', name: 'Nome', email: 'Email', subject: 'Assunto', message: 'Mensagem', submit: 'Enviar Mensagem', loading: 'Enviando...', success: 'Mensagem enviada com sucesso! Agradecemos o seu contato.', error: 'Ocorreu um erro ao enviar a mensagem. Por favor, tente novamente.' },
      info: { title: 'Nossas Informações', address: { title: 'Endereço', value: 'Rua Antônio Nápoli, 229<br/>Parada São Paulo - SP, 02987-030' }, phone: { title: 'Telefone', value: '(11) 5283-5040' }, email: { title: 'Email', value: 'contato@nowsolucoes.com.br' } }
    },
    solucoesPage: {
      hero: { title: 'Nossas Soluções', subtitle: 'Tecnologia e inovação para transformar a segurança e a gestão do seu condomínio.' },
      s1: { title: 'Área de Acesso', description: 'Soluções completas para controle de entrada e saída, incluindo reconhecimento facial, QR Code, convites digitais e integração com portaria remota para máxima segurança e conveniência.' },
      s2: { title: 'Área Externa', description: 'Monitoramento perimetral com câmeras de alta definição, cercas virtuais com inteligência artificial, alarmes sonoros e sensores de movimento para proteger o condomínio de ponta a ponta.' },
      s3: { title: 'Área Interna', description: 'Controle de acesso para áreas comuns como academias, salões de festas e piscinas. Garanta que apenas moradores autorizados utilizem os espaços, com relatórios de uso e agendamento via app.' },
      s4: { title: 'Facilities', description: 'Otimização da gestão de facilities com sistemas de automação para iluminação, controle de bombas de água e gerenciamento de manutenções preventivas, reduzindo custos e aumentando a eficiência.' },
      s5: { title: 'Soluções sob medida', description: 'Entendemos que cada condomínio é único. Desenvolvemos projetos personalizados que integram diferentes tecnologias para atender às suas necessidades específicas de segurança e gestão.' },
    },
    areaAcessoPage: {
      hero: { title: 'Área de Acesso', subtitle: 'Tecnologia de ponta para um controle de acesso seguro, ágil e totalmente integrado.' },
      intro: { title: 'Segurança e Conveniência na Entrada', description: 'Nossas soluções para áreas de acesso combinam as mais avançadas tecnologias para garantir que apenas pessoas autorizadas entrem no condomínio. Oferecemos um sistema robusto e flexível que se adapta às necessidades de moradores, visitantes e prestadores de serviço, tudo gerenciado de forma centralizada.' },
      products: {
        p1: { title: 'Controle Veicular (Tags RFID)', description: 'Agilize a entrada e saída de veículos com tags de radiofrequência. O sistema identifica automaticamente os carros cadastrados, abrindo o portão sem a necessidade de controles remotos.' },
        p2: { title: 'Liberação por QR Code', description: 'Gere convites digitais com QR Codes únicos para visitantes. Uma solução prática e segura que elimina a necessidade de interfonar e agiliza o acesso em dias de eventos.' },
        p3: { title: 'Biometria e Facial', description: 'Acesso rápido e seguro para moradores com o que há de mais moderno em reconhecimento biométrico e facial. Alta precisão e impossível de fraudar.' },
        p4: { title: 'Tablet para Portaria', description: 'Centralize o controle e o cadastro de visitantes e prestadores de serviço em um tablet intuitivo. Facilita o trabalho da portaria e mantém um registro digital de todos os acessos.' }
      }
    },
    areaInternaPage: {
      hero: { title: 'Área Interna', subtitle: 'Monitoramento e gestão inteligente para os espaços comuns do seu condomínio.' },
      intro: { title: 'Proteção e Eficiência Dentro do Condomínio', description: 'Garanta a segurança e o bom uso das áreas comuns com nossas soluções de monitoramento e gestão interna. Da vigilância por vídeo à automação de agendamentos, oferecemos ferramentas que trazem tranquilidade e organização para o dia a dia dos moradores.' },
      products: {
        p1: { title: 'Câmeras de Alta Resolução', description: 'Monitore corredores, elevadores, garagens e áreas de lazer com câmeras de alta definição, garantindo imagens nítidas para a segurança de todos.' },
        p2: { title: 'Análise de Comportamento por IA', description: 'Nossa IA detecta atividades suspeitas, como aglomerações ou comportamento incomum, e alerta a central de monitoramento em tempo real.' },
        p3: { title: 'Agendamento de Áreas Comuns', description: 'Gerencie a reserva de salões de festas, churrasqueiras e quadras através do nosso aplicativo. Simples para o morador, organizado para o síndico.' },
        p4: { title: 'Sensores IoT (Água/Gás)', description: 'Detecte vazamentos de água ou gás em áreas críticas e receba alertas imediatos, prevenindo acidentes e grandes prejuízos.' }
      }
    },
    areaExternaPage: {
      hero: { title: 'Área Externa', subtitle: 'Proteção perimetral inteligente para blindar seu condomínio contra ameaças.' },
      intro: { title: 'Vigilância que Nunca Dorme', description: 'A segurança do condomínio começa em seus limites. Nossas soluções para áreas externas utilizam inteligência artificial e tecnologia de ponta para criar uma barreira de proteção robusta, detectando ameaças antes que elas se aproximem.' },
      products: {
        p1: { title: 'Detecção de Intrusão (Cercas Virtuais)', description: 'Crie barreiras virtuais em muros e perímetros. Qualquer tentativa de invasão aciona um alarme instantâneo na central, permitindo uma resposta rápida.' },
        p2: { title: 'Leitura Automática de Placas (LPR)', description: 'Monitore todos os veículos que entram e saem do condomínio. O sistema LPR registra e armazena as placas, criando um histórico valioso para a segurança.' },
        p3: { title: 'Visão Térmica', description: 'Câmeras térmicas detectam a presença de pessoas e veículos no escuro total, em meio à neblina ou chuva, garantindo um monitoramento eficaz 24/7.' }
      }
    },
    facilitiesPage: {
      hero: { title: 'Facilities', subtitle: 'Otimize a gestão de recursos e manutenções com tecnologia e automação.' },
      intro: { title: 'Gestão Inteligente, Custos Reduzidos', description: 'Nossas soluções de facilities ajudam a automatizar tarefas, monitorar recursos e gerenciar a manutenção do condomínio de forma proativa. O resultado é mais eficiência operacional, redução de custos e maior vida útil para os equipamentos.' },
      products: {
        p1: { title: 'Wi-Fi de Alta Performance', description: 'Ofereça uma conexão de internet estável e de alta velocidade nas áreas comuns do condomínio, com gerenciamento centralizado e portal de acesso para visitantes.' },
        p2: { title: 'Switches Gerenciáveis', description: 'Construa uma infraestrutura de rede robusta e confiável para suportar todos os sistemas de segurança e automação do condomínio com total controle.' },
        p3: { title: 'Gestão de Manutenções', description: 'Agende e controle manutenções preventivas de elevadores, bombas e outros equipamentos através do nosso sistema, com alertas e relatórios automáticos.' },
        p4: { title: 'Integração com ERP', description: 'Conecte nossos sistemas de gestão e controle de acesso ao ERP da administradora, automatizando processos e centralizando as informações.' }
      }
    },
    solucoesSobMedidaPage: {
      hero: { title: 'Soluções Sob Medida', subtitle: 'Seu condomínio é único. Sua solução de segurança também deve ser.' },
      intro: { title: 'Criamos o Projeto Ideal para Você', description: 'Entendemos que não existe uma solução única para todos. Nossa equipe de especialistas está pronta para analisar as necessidades específicas do seu condomínio e desenhar um projeto de segurança e tecnologia totalmente personalizado. Combinamos diferentes tecnologias para criar um sistema integrado, eficiente e que cabe no seu orçamento.' },
      form: { title: 'Fale com um Especialista', subtitle: 'Preencha o formulário abaixo e um de nossos consultores entrará em contato para agendar uma conversa e entender seus desafios.' }
    },
    condominioInteligentePage: {
      hero: { title: 'Modernização, Segurança e Inteligência: O Futuro do seu Condomínio Começa Agora.', subtitle: 'Tecnologia de ponta SEM investimento inicial. Solução por assinatura mensal que garante a segurança e valorização do seu patrimônio.', cta: 'Solicite uma Análise Gratuita para o seu Condomínio' },
      socialProof1: { title: 'Quem Confia na NOW' },
      challenge: { title: 'O Desafio da Modernização Sem Comprometer o Caixa', c1: { title: 'Segurança Frágil', description: 'Monitoramento tradicional que reage, mas não previne.' }, c2: { title: 'Burocracia no Acesso', description: 'Filas, falhas no registro e vulnerabilidade na portaria.' }, c3: { title: 'Gestão Ineficiente', description: 'Processos manuais que consomem tempo do síndico e da administradora.' } },
      solution: { 
        title: 'Conheça os 4 Pilares do Condomínio Inteligente Now', 
        p1: { icon: 'security', title: 'Segurança Inteligente com IA', description: 'Sistema proativo que prevê e previne acidentes, com monitoramento 24/7.' }, 
        p2: { icon: 'wifi', title: 'Conectividade de Alta Performance', description: 'Internet estável e de alta velocidade em todas as áreas comuns.' }, 
        p3: { icon: 'devices', title: 'Gestão Digital e Automação', description: 'Otimização da rotina do síndico e do morador.' },
        p4: { icon: 'key', title: 'Controle de Acesso Avançado', description: 'Facilidade e segurança máxima no acesso de moradores e visitantes.' }
      },
      socialProof: { 
        title: 'Case de Sucesso', 
        subtitle: 'Assista e veja como o Condomínio Stilize se modernizou com um projeto personalizado NOW Soluções e conseguiu Zero Custo de Implementação.', 
        cta: 'Entenda o Modelo Financeiro que Viabilizou o Projeto Stilize.' 
      },
      detailedSolutions: { title: 'Tecnologia em Cada Canto do seu Condomínio', s1: { title: 'Área de Acesso', description: 'Controle Veicular (Tags RFID e LPR), Acesso de Pedestres (Reconhecimento Facial e Biometria), Gestão de Visitantes (QR Code e Click Aprova).' }, s2: { title: 'Área Interna e Externa', description: 'Segurança Proativa (Câmeras IA), Proteção Perimetral (Cercas Virtuais), Visão Térmica.' }, s3: { title: 'Facilities e Gestão', description: 'Conectividade Total (Wi-Fi e Cat6), Automação e IoT (Sensores de Vazamento), Gestão Simplificada (Agendamento, Controle de Entregas e Integração com ERP).' } },
      differentiator: { 
        title: 'Modernização Acessível:<br/>Tecnologia de Ponta sem Desembolso Inicial', 
        table: { 
          h1: 'Característica', 
          h2: 'Modelo Tradicional', 
          h3: 'Now Soluções', 
          r1: { feature: '<strong>Custo Inicial</strong>', traditional: 'Em média R$150.000 à vista', now: '<strong>R$0,00 - Zero Investimento</strong>' }, 
          r2: { feature: 'Manutenção e Suporte', traditional: 'Custo anual e por chamado', now: '<strong>Incluso e Ilimitado</strong>' }, 
          r3: { feature: 'Previsibilidade', traditional: 'Baixa (Custos variáveis)', now: '<strong>Total</strong> - Valor Fixo Mensal' },
          r4: { feature: 'Assembleia', traditional: 'Necessária aprovação de 2/3 dos condôminos', now: '<strong>Aprovação simples</strong> (maioria simples)' },
          r5: { feature: 'Suporte Técnico', traditional: 'Atendimento em horário comercial', now: '<strong>24 horas por dia, 7 dias por semana</strong>' },
          r6: { feature: 'Atualizações e Garantia', traditional: 'Custo adicional, garantia limitada', now: '<strong>Inclusa</strong> e garantida durante todo o contrato' } 
        } 
      },
      finalCta: { title: 'Pare de Adiar a Segurança e a Eficiência do seu Condomínio.', subtitle: 'Dê o primeiro passo para ter um condomínio mais seguro, eficiente e valorizado. Solicite agora uma análise técnica e descubra o plano ideal para a sua realidade.', cta: 'Solicitar uma Demonstração ou Estudo de Viabilidade Gratuito' }
    },
    metadata: {
      home: { title: 'Now Soluções | Mais controle, menos custos.', description: 'Now Soluções: Especialistas em tecnologia para condomínios inteligentes. Oferecemos controle de acesso, monitoramento com IA, armários inteligentes e mais.', keywords: 'condomínio inteligente, segurança condominial, controle de acesso, portaria remota, now soluções' },
      quemSomos: { title: 'Sobre Nós | Now Soluções', description: 'Conheça a história e os valores da Now Soluções, a empresa que está revolucionando a gestão de condomínios com tecnologia de ponta e foco no cliente.', keywords: 'sobre now soluções, história, valores, equipe, gestão condominial' },
      contato: { title: 'Contato | Now Soluções', description: 'Entre em contato com a Now Soluções. Tire suas dúvidas, solicite um orçamento ou fale com nossa equipe de especialistas em segurança e tecnologia para condomínios.', keywords: 'contato now soluções, telefone, email, endereço, orçamento condomínio' },
      solucoes: { title: 'Nossas Soluções | Now Soluções', description: 'Descubra as soluções da Now para áreas de acesso, áreas externas, internas, facilities e projetos sob medida para o seu condomínio.', keywords: 'soluções condominiais, área de acesso, monitoramento ia, facilities, projetos personalizados' },
      areaAcesso: { title: 'Área de Acesso | Now Soluções', description: 'Soluções de controle de acesso veicular, QR Code, biometria e facial para condomínios.', keywords: 'controle de acesso, rfid, qr code, biometria, portaria' },
      areaInterna: { title: 'Área Interna | Now Soluções', description: 'Monitoramento com câmeras de alta resolução, análise de comportamento e gestão de áreas comuns.', keywords: 'câmeras de segurança, ia, agendamento de áreas, sensores iot' },
      areaExterna: { title: 'Área Externa | Now Soluções', description: 'Proteção perimetral com cercas virtuais, leitura de placas (LPR) e visão térmica.', keywords: 'cerca virtual, lpr, leitura de placa, visão térmica, segurança perimetral' },
      facilities: { title: 'Facilities | Now Soluções', description: 'Otimize a gestão de facilities com Wi-Fi de alta performance, switches e gestão de manutenções.', keywords: 'facilities, gestão de manutenção, wifi condominial, switches' },
      solucoesSobMedida: { title: 'Soluções Sob Medida | Now Soluções', description: 'Projetos personalizados de segurança e tecnologia para atender as necessidades únicas do seu condomínio.', keywords: 'projetos personalizados, segurança condominial, consultoria de segurança' }
    },
    whatsappTooltip: 'Fale com um especialista'
  },
  'en-US': {
    nav: { home: 'Home', smartCondo: 'Smart Condominium', solutions: 'Our Solutions', about: 'About Us', contact: 'Contact' },
    solutionsSub: { access: 'Access Area', external: 'External Area', internal: 'Internal Area', facilities: 'Facilities', custom: 'Custom Solutions' },
    header: { cta: 'Request a Quote' },
    hero: { slide1: { title: 'Cameras with Artificial<br/>Intelligence', subtitle: 'With Now Soluções, your condominium has smart cameras that identify movements, trigger sensors, and create virtual barriers. More precision, more protection, less worry.' }, slide2: { title: 'Smart and Uncomplicated<br/>Access', subtitle: 'Facial recognition, QR Code, and vehicle recognition. Offer security and convenience for residents and visitors with the highest technology.' }, slide3: { title: 'Complete Management<br/>in Your Palm', subtitle: 'Our application centralizes all functionalities, from visitor authorization to booking common areas. Efficient and transparent management.' }, cta: 'Speak with an expert' },
    impact: { title: 'Our Impact', stat1: { value: '+80', label: 'Condominiums served' }, stat2: { value: '+15', label: 'Years of Market Experience' }, stat3: { value: '+15k', label: 'Residents Impacted' }, stat4: { value: '98%', label: 'Satisfaction among managers' } },
    solutions: { title: 'Your condominium smarter. Your life safer.', subtitle: 'We combine cutting-edge technology, close customer service, and personalized solutions to transform the routine of residential and commercial condominiums. Each service is developed to offer more security, convenience, and peace of mind for managers, residents, and administrators.', card1: { title: 'Smart Access', description: 'Facial recognition, QR Code, digital invitations, vehicle recognition, and remote release via app.' }, card2: { title: 'AI Monitoring', description: 'Cameras with artificial intelligence, virtual fences, sound alarms, and sensors with behavior analysis.' }, card3: { title: 'Smart Lockers', description: '24/7 package receiving with security and autonomy. Notifications via app for pickup.' } },
    about: { tagline: 'DIFFERENTIALS', title: 'Why choose Now?', description: 'We have the smart, tailor-made solution for the reality of each condominium. We accompany managers and administrators at every stage, from diagnosis to operation, with dedicated support, cutting-edge technology, and a total focus on security, efficiency, and peace of mind.', partnersTagline: 'OUR PARTNERS' },
    cta: { title: 'Excellence in every detail', description: 'Our commitment is to deliver solutions that truly work. With cutting-edge technology, a specialized team, and continuous support, we offer a secure, fluid, and efficient condominium management experience.', button: 'Speak with an expert' },
    testimonials: { title: "What our clients say", t1: { quote: 'With Now, we were able to organize all communication and control of our condominium. The app has made life much easier for everyone.', name: 'Carlos Mendes', title: 'manager', company: 'Vila Serena Condominium' }, t2: { quote: 'The facial access system and smart lockers have completely changed our routine. We are safer and more organized.', name: 'Ana Lúcia Barros', title: 'administrator', company: 'Smart Park Alphaville' }, t3: { quote: 'Agile and efficient technical support. The Now team is always ready to assist us, which makes all the difference in daily management.', name: 'Roberto Almeida', title: 'manager', company: 'Corporate Tower Building' } },
    footer: { description: 'Now Soluções - We connect security, technology, and management to transform your condominium.', nav: { home: 'Home', about: 'About Us', contact: 'Contact', privacy: 'Privacy Policy' }, solutions: { smartCondo: 'Smart Condominium', access: 'Access Area', external: 'External Area', internal: 'Internal Area', facilities: 'Facilities', custom: 'Custom Solutions' }, contact: { phone: '+55 (11) 5283-5040', address: 'Antônio Nápoli St, 229<br/>Parada São Paulo - SP<br/>02987-030, Brazil' }, copyright: '© Now Soluções | All rights reserved | 2025' },
    quemSomos: { hero: { title: 'About Now Soluções', subtitle: 'Connecting technology, security, and people to create smarter condominiums and stronger communities.' }, story: { tagline: 'OUR JOURNEY', title: 'Born to innovate', p1: 'Now Soluções was founded with the mission to revolutionize condominium management in Brazil. We realized that technology could be a powerful ally for managers and residents, bringing more security, efficiency, and peace of mind to daily life. From the beginning, our focus has been to develop and integrate solutions that truly make a difference.', p2: 'With over 15 years of combined experience in the technology and security sector, our team is dedicated to understanding the unique challenges of each condominium, offering personalized service and support that goes beyond expectations.' }, values: { title: 'Our Values', v1: { title: 'Innovation', description: 'We constantly seek the most advanced solutions to ensure the technological forefront in security and management.' }, v2: { title: 'Security', description: "Our clients' protection is our highest priority, reflected in every product and service we offer." }, v3: { title: 'Customer Focus', description: 'We work in partnership with managers and residents to understand and meet their real needs with excellence.' } }, partners: { title: 'Companies that trust our work' } },
    contato: { hero: { title: 'Contact Us', subtitle: 'Have a question or want to request a quote? Our team is ready to help.' }, form: { title: 'Send a message', subtitle: 'Fill out the form, and we will get in touch as soon as possible.', name: 'Name', email: 'Email', subject: 'Subject', message: 'Message', submit: 'Send Message', loading: 'Sending...', success: 'Message sent successfully! Thank you for your contact.', error: 'An error occurred while sending the message. Please try again.' }, info: { title: 'Our Information', address: { title: 'Address', value: 'Antônio Nápoli St, 229<br/>Parada São Paulo - SP, 02987-030, Brazil' }, phone: { title: 'Phone', value: '+55 (11) 5283-5040' }, email: { title: 'Email', value: 'contato@nowsolucoes.com.br' } } },
    solucoesPage: { hero: { title: 'Our Solutions', subtitle: 'Technology and innovation to transform the security and management of your condominium.' }, s1: { title: 'Access Area', description: 'Complete solutions for entry and exit control, including facial recognition, QR Code, digital invitations, and integration with remote concierge for maximum security and convenience.' }, s2: { title: 'External Area', description: 'Perimeter monitoring with high-definition cameras, virtual fences with artificial intelligence, sound alarms, and motion sensors to protect the condominium from end to end.' }, s3: { title: 'Internal Area', description: 'Access control for common areas such as gyms, party rooms, and pools. Ensure that only authorized residents use the spaces, with usage reports and scheduling via the app.' }, s4: { title: 'Facilities', description: 'Optimization of facilities management with automation systems for lighting, water pump control, and preventive maintenance management, reducing costs and increasing efficiency.' }, s5: { title: 'Custom Solutions', description: 'We understand that each condominium is unique. We develop customized projects that integrate different technologies to meet your specific security and management needs.' } },
    areaAcessoPage: { hero: { title: 'Access Area', subtitle: 'Cutting-edge technology for secure, agile, and fully integrated access control.' }, intro: { title: 'Security and Convenience at the Entrance', description: 'Our access area solutions combine the most advanced technologies to ensure only authorized individuals enter the condominium. We offer a robust and flexible system that adapts to the needs of residents, visitors, and service providers, all managed centrally.' }, products: { p1: { title: 'Vehicle Control (RFID Tags)', description: 'Speed up vehicle entry and exit with radio frequency tags. The system automatically identifies registered cars, opening the gate without the need for remote controls.' }, p2: { title: 'QR Code Release', description: 'Generate digital invitations with unique QR codes for visitors. A practical and secure solution that eliminates the need to use the intercom and speeds up access on event days.' }, p3: { title: 'Biometrics and Facial Recognition', description: 'Fast and secure access for residents with the latest in biometric and facial recognition. High accuracy and impossible to defraud.' }, p4: { title: 'Concierge Tablet', description: 'Centralize the control and registration of visitors and service providers on an intuitive tablet. It facilitates the concierge\'s work and maintains a digital record of all accesses.' } } },
    areaInternaPage: { hero: { title: 'Internal Area', subtitle: 'Intelligent monitoring and management for your condominium\'s common spaces.' }, intro: { title: 'Protection and Efficiency Inside the Condominium', description: 'Ensure the security and proper use of common areas with our internal monitoring and management solutions. From video surveillance to scheduling automation, we provide tools that bring peace of mind and organization to residents\' daily lives.' }, products: { p1: { title: 'High-Resolution Cameras', description: 'Monitor hallways, elevators, garages, and leisure areas with high-definition cameras, ensuring clear images for everyone\'s safety.' }, p2: { title: 'AI Behavior Analysis', description: 'Our AI detects suspicious activities, such as loitering or unusual behavior, and alerts the monitoring center in real-time.' }, p3: { title: 'Common Area Scheduling', description: 'Manage reservations for party rooms, barbecue areas, and courts through our app. Simple for the resident, organized for the manager.' }, p4: { title: 'IoT Sensors (Water/Gas)', description: 'Detect water or gas leaks in critical areas and receive immediate alerts, preventing accidents and major damages.' } } },
    areaExternaPage: { hero: { title: 'External Area', subtitle: 'Intelligent perimeter protection to shield your condominium from threats.' }, intro: { title: 'Vigilance That Never Sleeps', description: 'The security of the condominium begins at its boundaries. Our external area solutions use artificial intelligence and cutting-edge technology to create a robust protective barrier, detecting threats before they get close.' }, products: { p1: { title: 'Intrusion Detection (Virtual Fences)', description: 'Create virtual barriers on walls and perimeters. Any invasion attempt triggers an instant alarm at the central station, allowing for a rapid response.' }, p2: { title: 'Automatic License Plate Reading (LPR)', description: 'Monitor all vehicles entering and leaving the condominium. The LPR system records and stores license plates, creating a valuable security history.' }, p3: { title: 'Thermal Vision', description: 'Thermal cameras detect the presence of people and vehicles in total darkness, through fog or rain, ensuring effective 24/7 monitoring.' } } },
    facilitiesPage: { hero: { title: 'Facilities', subtitle: 'Optimize resource and maintenance management with technology and automation.' }, intro: { title: 'Smart Management, Reduced Costs', description: 'Our facilities solutions help automate tasks, monitor resources, and manage condominium maintenance proactively. The result is greater operational efficiency, cost reduction, and a longer lifespan for equipment.' }, products: { p1: { title: 'High-Performance Wi-Fi', description: 'Offer a stable, high-speed internet connection in the condominium\'s common areas, with centralized management and a visitor access portal.' }, p2: { title: 'Managed Switches', description: 'Build a robust and reliable network infrastructure to support all security and automation systems of the condominium with full control.' }, p3: { title: 'Maintenance Management', description: 'Schedule and control preventive maintenance for elevators, pumps, and other equipment through our system, with automatic alerts and reports.' }, p4: { title: 'ERP Integration', description: 'Connect our management and access control systems to the administrator\'s ERP, automating processes and centralizing information.' } } },
    solucoesSobMedidaPage: { hero: { title: 'Custom Solutions', subtitle: 'Your condominium is unique. Your security solution should be too.' }, intro: { title: 'We Create the Ideal Project for You', description: 'We understand that there is no one-size-fits-all solution. Our team of experts is ready to analyze the specific needs of your condominium and design a fully customized security and technology project. We combine different technologies to create an integrated, efficient system that fits your budget.' }, form: { title: 'Speak with a Specialist', subtitle: 'Fill out the form below, and one of our consultants will contact you to schedule a conversation and understand your challenges.' } },
    condominioInteligentePage: {
      hero: { title: 'Modernization, Security and Intelligence: Your Condominium\'s Future Starts Now.', subtitle: 'Cutting-edge technology with NO initial investment. Monthly subscription solution that guarantees the security and appreciation of your property.', cta: 'Request a Free Analysis for Your Condominium' },
      socialProof1: { title: 'Who Trusts NOW' },
      challenge: { title: 'The Challenge of Modernizing Without Compromising Cash Flow', c1: { title: 'Fragile Security', description: 'Traditional monitoring that reacts but does not prevent.' }, c2: { title: 'Access Bureaucracy', description: 'Queues, registration failures, and vulnerability at the entrance.' }, c3: { title: 'Inefficient Management', description: 'Manual processes that consume the manager\'s and administrator\'s time.' } },
      solution: { 
        title: 'Conheça os 4 Pilares do Condomínio Inteligente Now', 
        p1: { icon: 'security', title: 'Smart Security with AI', description: 'Proactive system that predicts and prevents accidents, with 24/7 monitoring.' }, 
        p2: { icon: 'wifi', title: 'High-Performance Connectivity', description: 'Stable, high-speed internet in all common areas.' }, 
        p3: { icon: 'devices', title: 'Digital Management and Automation', description: 'Optimization of the manager\'s and resident\'s routine.' },
        p4: { icon: 'key', title: 'Advanced Access Control', description: 'Maximum ease and security in accessing for residents and visitors.' }
      },
      socialProof: { 
        title: 'Case de Sucesso', 
        subtitle: 'Watch and see how Condomínio Stilize modernized with a customized NOW Soluções project and achieved Zero Implementation Cost.', 
        cta: 'Understand the Financial Model that Made the Stilize Project Viable.' 
      },
      detailedSolutions: { title: 'Tecnologia em Cada Canto do seu Condomínio', s1: { title: 'Access Area', description: 'Vehicle Control (RFID & LPR Tags), Pedestrian Access (Facial & Biometric Recognition), Visitor Management (QR Code & Click Approve).' }, s2: { title: 'Internal and External Area', description: 'Proactive Security (AI Cameras), Perimeter Protection (Virtual Fences), Thermal Vision.' }, s3: { title: 'Facilities and Management', description: 'Total Connectivity (Wi-Fi & Cat6), Automation & IoT (Leak Sensors), Simplified Management (Scheduling, Delivery Control & ERP Integration).' } },
      differentiator: { 
        title: 'Modernização Acessível:<br/>Tecnologia de Ponta sem Desembolso Inicial', 
        table: { 
          h1: 'Feature', 
          h2: 'Traditional Model', 
          h3: 'Now Soluções', 
          r1: { feature: '<strong>Initial Cost</strong>', traditional: 'Average of R$150,000 upfront', now: '<strong>R$0.00 - Zero Investment</strong>' }, 
          r2: { feature: 'Maintenance and Support', traditional: 'Annual cost and per-call fee', now: '<strong>Included and Unlimited</strong>' }, 
          r3: { feature: 'Predictability', traditional: 'Low (Variable costs)', now: '<strong>Total</strong> - Fixed Monthly Fee' },
          r4: { feature: 'Assembleia', traditional: 'Necessária aprovação de 2/3 dos condôminos', now: '<strong>Aprovação simples</strong> (maioria simples)' },
          r5: { feature: 'Suporte Técnico', traditional: 'Atendimento em horário comercial', now: '<strong>24 horas por dia, 7 dias por semana</strong>' },
          r6: { feature: 'Updates and Warranty', traditional: 'Additional cost, limited warranty', now: '<strong>Included</strong> and guaranteed throughout the contract' } 
        } 
      },
      finalCta: { title: 'Stop Postponing Your Condominium\'s Security and Efficiency.', subtitle: 'Take the first step towards a safer, more efficient, and more valuable condominium. Request a technical analysis now and discover the ideal plan for your reality.', cta: 'Request a Free Demonstration or Feasibility Study' }
    },
    metadata: { home: { title: 'Now Soluções | More control, less costs.', description: 'Now Soluções: Specialists in smart condominium technology. We offer access control, AI monitoring, smart lockers, and more.', keywords: 'smart condominium, condo security, access control, remote doorman, now soluções' }, quemSomos: { title: 'About Us | Now Soluções', description: 'Learn about the history and values of Now Soluções, the company revolutionizing condominium management with cutting-edge technology and customer focus.', keywords: 'about now soluções, history, values, team, condominium management' }, contato: { title: 'Contact | Now Soluções', description: 'Get in touch with Now Soluções. Ask questions, request a quote, or speak with our team of specialists in security and technology for condominiums.', keywords: 'contact now soluções, phone, email, address, condo quote' }, solucoes: { title: 'Our Solutions | Now Soluções', description: 'Discover Now’s solutions for access areas, external and internal areas, facilities, and custom projects for your condominium.', keywords: 'condo solutions, access area, AI monitoring, facilities, custom projects' }, areaAcesso: { title: 'Access Area | Now Soluções', description: 'Vehicle access control, QR Code, biometric, and facial recognition solutions for condominiums.', keywords: 'access control, rfid, qr code, biometrics, concierge' }, areaInterna: { title: 'Internal Area | Now Soluções', description: 'Monitoring with high-resolution cameras, behavior analysis, and common area management.', keywords: 'security cameras, ai, area scheduling, iot sensors' }, areaExterna: { title: 'External Area | Now Soluções', description: 'Perimeter protection with virtual fences, license plate reading (LPR), and thermal vision.', keywords: 'virtual fence, lpr, license plate reading, thermal vision, perimeter security' }, facilities: { title: 'Facilities | Now Soluções', description: 'Optimize facilities management with high-performance Wi-Fi, switches, and maintenance management.', keywords: 'facilities, maintenance management, condo wifi, switches' }, solucoesSobMedida: { title: 'Custom Solutions | Now Soluções', description: 'Custom security and technology projects to meet the unique needs of your condominium.', keywords: 'custom projects, condo security, security consulting' } }
    ,
    whatsappTooltip: 'Speak with an expert'
  },
  'es-ES': {
    nav: { home: 'Inicio', smartCondo: 'Condominio inteligente', solutions: 'Nuestras Soluciones', about: 'Quiénes Somos', contact: 'Contacto' },
    solutionsSub: { access: 'Área de Acceso', external: 'Área Externa', internal: 'Área Interna', facilities: 'Servicios', custom: 'Soluciones a Medida' },
    header: { cta: 'Solicitar Presupuesto' },
    hero: { slide1: { title: 'Cámaras con inteligencia<br/>artificial', subtitle: 'Con Now Soluções, su condominio cuenta con cámaras inteligentes que identifican movimientos, activan sensores y crean barreras virtuales. Más precisión, más protección, menos preocupaciones.' }, slide2: { title: 'Acceso Inteligente<br/>y Sencillo', subtitle: 'Control facial, Código QR y reconocimiento de vehículos. Ofrezca seguridad y practicidad a residentes y visitantes con la más alta tecnología.' }, slide3: { title: 'Gestión Completa<br/>en la Palma de la Mano', subtitle: 'Nuestra aplicación centraliza todas las funcionalidades, desde la autorización de visitantes hasta la reserva de áreas comunes. Gestión eficiente y transparente.' }, cta: 'Hable con un experto' },
    impact: { title: 'Nuestro Impacto', stat1: { value: '+80', label: 'Condominios atendidos' }, stat2: { value: '+15', label: 'Años de Experiencia en el Mercado' }, stat3: { value: '+15k', label: 'Residentes Impactados' }, stat4: { value: '98%', label: 'Satisfacción entre administradores' } },
    solutions: { title: 'Su condominio más inteligente. Su vida más segura.', subtitle: 'Combinamos tecnología de punta, atención cercana y soluciones personalizadas para transformar la rutina de condominios residenciales y comerciales. Cada servicio está desarrollado para ofrecer más seguridad, practicidad y tranquilidad a administradores, residentes y gestores.', card1: { title: 'Acceso Inteligente', description: 'Control facial, Código QR, invitaciones digitales, reconocimiento de vehículos y liberación remota vía app.' }, card2: { title: 'Monitoreo con IA', description: 'Cámaras con inteligencia artificial, cercas virtuales, alarmas sonoras y sensores con análisis de comportamiento.' }, card3: { title: 'Casilleros Inteligentes', description: 'Recepción de paquetes 24/7 con seguridad y autonomía. Notificaciones vía app para su recogida.' } },
    about: { tagline: 'DIFERENCIALES', title: '¿Por qué elegir Now?', description: 'Tenemos la solución inteligente y a medida para la realidad de cada condominio. Acompañamos a los administradores y gestores en todas las etapas, desde el diagnóstico hasta la operación, con soporte dedicado, tecnología de punta y un enfoque total en seguridad, eficiencia y tranquilidad.', partnersTagline: 'NUESTROS SOCIOS' },
    cta: { title: 'Excelencia en cada detalle', description: 'Nuestro compromiso es entregar soluciones que realmente funcionan. Con tecnología de punta, un equipo especializado y soporte continuo, ofrecemos una experiencia de gestión de condominios segura, fluida y eficiente.', button: 'Hable con un experto' },
    testimonials: { title: 'Lo que dicen nuestros clientes', t1: { quote: 'Con Now logramos organizar toda la comunicación y control de nuestro condominio. La aplicación facilitó mucho la vida de todos.', name: 'Carlos Mendes', title: 'administrador', company: 'Condominio Vila Serena' }, t2: { quote: 'El sistema de acceso facial y los casilleros inteligentes cambiaron por completo nuestra rutina. Estamos más seguros y organizados.', name: 'Ana Lúcia Barros', title: 'gestora', company: 'Smart Park Alphaville' }, t3: { quote: 'Soporte técnico ágil y eficiente. El equipo de Now siempre está listo para atendernos, lo que marca toda la diferencia en la gestión diaria.', name: 'Roberto Almeida', title: 'administrador', company: 'Edificio Corporate Tower' } },
    footer: { description: 'Now Soluções - Conectamos seguridad, tecnología y gestión para transformar su condominio.', nav: { home: 'Inicio', about: 'Quiénes Somos', contact: 'Contacto', privacy: 'Política de Privacidad' }, solutions: { smartCondo: 'Condominio Inteligente', access: 'Área de Acceso', external: 'Área Externa', internal: 'Área Interna', facilities: 'Servicios', custom: 'Soluciones a Medida' }, contact: { phone: '+55 (11) 5283-5040', address: 'Calle Antônio Nápoli, 229<br/>Parada São Paulo - SP<br/>02987-030, Brasil' }, copyright: '© Now Soluções | Todos los derechos reservados | 2025' },
    quemSomos: { hero: { title: 'Sobre Now Soluções', subtitle: 'Conectando tecnología, seguridad y personas para crear condominios más inteligentes y comunidades más fuertes.' }, story: { tagline: 'NUESTRA TRAYECTORIA', title: 'Nacimos para innovar', p1: 'Now Soluções fue fundada con la misión de revolucionar la gestión de condominios en Brasil. Nos dimos cuenta de que la tecnología podría ser un poderoso aliado para administradores y residentes, aportando más seguridad, eficiencia y tranquilidad al día a día. Desde el principio, nuestro enfoque ha sido desarrollar e integrar soluciones que realmente marcan la diferencia.', p2: 'Con más de 15 años de experiencia combinada en el sector de la tecnología y la seguridad, nuestro equipo se dedica a comprender los desafíos únicos de cada condominio, ofreciendo un servicio personalizado y un soporte que supera las expectativas.' }, values: { title: 'Nuestros Valores', v1: { title: 'Innovación', description: 'Buscamos constantemente las soluciones más avanzadas para garantizar la vanguardia tecnológica en seguridad y gestión.' }, v2: { title: 'Seguridad', description: 'La protección de nuestros clientes es nuestra máxima prioridad, reflejada en cada producto y servicio que ofrecemos.' }, v3: { title: 'Enfoque en el Cliente', description: 'Trabajamos en colaboración con administradores y residentes para comprender y satisfacer sus necesidades reales con excelencia.' } }, partners: { title: 'Empresas que confían en nuestro trabajo' } },
    contato: { hero: { title: 'Contáctenos', subtitle: '¿Tiene alguna pregunta o desea solicitar un presupuesto? Nuestro equipo está listo para ayudar.' }, form: { title: 'Envíe un mensaje', subtitle: 'Complete el formulario y nos pondremos en contacto lo antes posible.', name: 'Nombre', email: 'Correo Electrónico', subject: 'Asunto', message: 'Mensaje', submit: 'Enviar Mensaje', loading: 'Enviando...', success: '¡Mensaje enviado con éxito! Gracias por su contacto.', error: 'Ocurrió un error al enviar el mensaje. Por favor, inténtelo de nuevo.' }, info: { title: 'Nuestra Información', address: { title: 'Dirección', value: 'Calle Antônio Nápoli, 229<br/>Parada São Paulo - SP, 02987-030, Brasil' }, phone: { title: 'Teléfono', value: '+55 (11) 5283-5040' }, email: { title: 'Correo Electrónico', value: 'contato@nowsolucoes.com.br' } } },
    solucoesPage: { hero: { title: 'Nuestras Soluciones', subtitle: 'Tecnología e innovación para transformar la seguridad y la gestión de su condominio.' }, s1: { title: 'Área de Acceso', description: 'Soluciones completas para control de entrada y salida, incluyendo reconocimiento facial, Código QR, invitaciones digitales e integración con conserjería remota para máxima seguridad y comodidad.' }, s2: { title: 'Área Externa', description: 'Monitoreo perimetral con cámaras de alta definición, cercas virtuales con inteligencia artificial, alarmas sonoras y sensores de movimiento para proteger el condominio de extremo a extremo.' }, s3: { title: 'Área Interna', description: 'Control de acceso para áreas comunes como gimnasios, salones de fiestas y piscinas. Asegúrese de que solo los residentes autorizados utilicen los espacios, con informes de uso y programación a través de la aplicación.' }, s4: { title: 'Servicios', description: 'Optimización de la gestión de servicios con sistemas de automatización para iluminación, control de bombas de agua y gestión de mantenimiento preventivo, reduciendo costos y aumentando la eficiencia.' }, s5: { title: 'Soluciones a Medida', description: 'Entendemos que cada condominio es único. Desarrollamos proyectos personalizados que integran diferentes tecnologías para satisfacer sus necesidades específicas de seguridad y gestión.' } },
    areaAcessoPage: { hero: { title: 'Área de Acceso', subtitle: 'Tecnología de vanguardia para un control de acceso seguro, ágil y totalmente integrado.' }, intro: { title: 'Seguridad y Comodidad en la Entrada', description: 'Nuestras soluciones para áreas de acceso combinan las tecnologías más avanzadas para garantizar que solo personas autorizadas ingresen al condominio. Ofrecemos un sistema robusto y flexible que se adapta a las necesidades de residentes, visitantes y proveedores de servicios, todo gestionado de forma centralizada.' }, products: { p1: { title: 'Control Vehicular (Etiquetas RFID)', description: 'Agilice la entrada y salida de vehículos con etiquetas de radioffrecuencia. El sistema identifica automáticamente los autos registrados, abriendo el portón sin necesidad de controles remotos.' }, p2: { title: 'Liberación por Código QR', description: 'Genere invitaciones digitales con códigos QR únicos para visitantes. Una solución práctica y segura que elimina la necesidad de usar el interfono y agiliza el acceso en días de eventos.' }, p3: { title: 'Biometría y Reconocimiento Facial', description: 'Acceso rápido y seguro para residentes con lo último en reconocimiento biométrico y facial. Alta precisión e imposible de falsificar.' }, p4: { title: 'Tableta para Conserjería', description: 'Centralice el control y registro de visitantes y proveedores de servicios en una tableta intuitiva. Facilita el trabajo de la conserjería y mantiene un registro digital de todos los accesos.' } } },
    areaInternaPage: { hero: { title: 'Área Interna', subtitle: 'Monitoreo y gestión inteligente para los espacios comunes de su condominio.' }, intro: { title: 'Protección y Eficiencia Dentro del Condominio', description: 'Garantice la seguridad y el buen uso de las áreas comunes con nuestras soluciones de monitoreo y gestión interna. Desde la videovigilancia hasta la automatización de reservas, ofrecemos herramientas que brindan tranquilidad y organización a la vida diaria de los residentes.' }, products: { p1: { title: 'Cámaras de Alta Resolución', description: 'Monitoree pasillos, ascensores, garajes y áreas de ocio con cámaras de alta definición, garantizando imágenes nítidas para la seguridad de todos.' }, p2: { title: 'Análisis de Comportamiento con IA', description: 'Nuestra IA detecta actividades sospechosas, como merodeo o comportamiento inusual, y alerta al centro de monitoreo en tiempo real.' }, p3: { title: 'Reserva de Áreas Comunes', description: 'Gestione la reserva de salones de fiestas, áreas de barbacoa y canchas a través de nuestra aplicación. Simple para el residente, organizado para el administrador.' }, p4: { title: 'Sensores IoT (Agua/Gas)', description: 'Detecte fugas de agua o gas en áreas críticas y reciba alertas inmediatas, previniendo accidentes y daños mayores.' } } },
    areaExternaPage: { hero: { title: 'Área Externa', subtitle: 'Protección perimetral inteligente para blindar su condominio contra amenazas.' }, intro: { title: 'Vigilancia que Nunca Duerme', description: 'La seguridad del condominio comienza en sus límites. Nuestras soluciones para áreas externas utilizan inteligencia artificial y tecnología de punta para crear una barrera de protección robusta, detectando amenazas antes de que se acerquen.' }, products: { p1: { title: 'Detección de Intrusión (Cercas Virtuales)', description: 'Cree barreras virtuales en muros y perímetros. Cualquier intento de invasión activa una alarma instantánea en la central, permitiendo una respuesta rápida.' }, p2: { title: 'Lectura Automática de Matrículas (LPR)', description: 'Monitoree todos los vehículos que entran y salen del condominio. El sistema LPR registra y almacena las matrículas, creando un valioso historial de seguridad.' }, p3: { title: 'Visión Térmica', description: 'Las cámaras térmicas detectan la presencia de personas y vehículos en total oscuridad, a través de la niebla o la lluvia, garantizando un monitoreo eficaz 24/7.' } } },
    facilitiesPage: { hero: { title: 'Servicios', subtitle: 'Optimice la gestión de recursos y mantenimientos con tecnología y automatización.' }, intro: { title: 'Gestión Inteligente, Costos Reducidos', description: 'Nuestras soluciones de servicios ayudan a automatizar tareas, monitorear recursos y gestionar el mantenimiento del condominio de forma proactiva. El resultado es una mayor eficiencia operativa, reducción de costos y una vida útil más larga para los equipos.' }, products: { p1: { title: 'Wi-Fi de Alto Rendimiento', description: 'Ofrezca una conexión a internet estable y de alta velocidad en las áreas comunes del condominio, con gestión centralizada y un portal de acceso para visitantes.' }, p2: { title: 'Switches Gestionables', description: 'Construya una infraestructura de red robusta y confiable para soportar todos los sistemas de seguridad y automatización del condominio con control total.' }, p3: { title: 'Gestión de Mantenimientos', description: 'Programe y controle mantenimientos preventivos de ascensores, bombas y otros equipos a través de nuestro sistema, con alertas e informes automáticos.' }, p4: { title: 'Integración con ERP', description: 'Conecte nuestros sistemas de gestión y control de acceso al ERP del administrador, automatizando procesos y centralizando la información.' } } },
    solucoesSobMedidaPage: { hero: { title: 'Soluciones a Medida', subtitle: 'Su condominio es único. Su solución de seguridad también debe serlo.' }, intro: { title: 'Creamos el Proyecto Ideal para Usted', description: 'Entendemos que no existe una solución única para todos. Nuestro equipo de expertos está listo para analizar las necesidades específicas de su condominio y diseñar un proyecto de seguridad y tecnología totalmente personalizado. Combinamos diferentes tecnologías para crear un sistema integrado, eficiente y que se ajuste a su presupuesto.' }, form: { title: 'Hable con un Especialista', subtitle: 'Complete el formulario a continuación y uno de nuestros consultores se pondrá en contacto para programar una conversación y comprender sus desafíos.' } },
    condominioInteligentePage: {
      hero: { title: 'Modernización, Seguridad e Inteligencia: El Futuro de su Condominio Comienza Ahora.', subtitle: 'Tecnología de punta SIN inversión inicial. Solución por suscripción mensual que garantiza la seguridad y valorización de su patrimonio.', cta: 'Solicite un Análisis Gratuito para su Condominio' },
      socialProof1: { title: 'Quién Confía en NOW' },
      challenge: { title: 'El Desafío de la Modernización Sin Comprometer el Flujo de Caja', c1: { title: 'Seguridad Frágil', description: 'Monitoreo tradicional que reacciona, pero no previene.' }, c2: { title: 'Burocracia en el Acceso', description: 'Colas, fallos en el registro y vulnerabilidad en la portería.' }, c3: { title: 'Gestión Ineficiente', description: 'Procesos manuales que consumen el tiempo del administrador y del gestor.' } },
      solution: { 
        title: 'Conheça os 4 Pilares do Condomínio Inteligente Now', 
        p1: { icon: 'security', title: 'Seguridad Inteligente con IA', description: 'Sistema proactivo que predice y previene accidentes, con monitoreo 24/7.' }, 
        p2: { icon: 'wifi', title: 'Conectividad de Alto Rendimiento', description: 'Internet estable y de alta velocidad en todas las áreas comunes.' }, 
        p3: { icon: 'devices', title: 'Gestión Digital y Automatización', description: 'Optimización de la rutina del administrador y del residente.' },
        p4: { icon: 'key', title: 'Control de Acceso Avanzado', description: 'Máxima facilidad y seguridad en el acceso de residentes y visitantes.' }
      },
      socialProof: { 
        title: 'Case de Sucesso', 
        subtitle: 'Vea y descubra cómo el Condominio Stilize se modernizó con un proyecto personalizado NOW Soluções y logró Cero Costo de Implementación.', 
        cta: 'Entienda el Modelo Financiero que Hizo Viable el Proyecto Stilize.' 
      },
      detailedSolutions: { title: 'Tecnologia em Cada Canto do seu Condomínio', s1: { title: 'Área de Acceso', description: 'Control Vehicular (Etiquetas RFID y LPR), Acceso Peatonal (Reconocimiento Facial y Biometría), Gestión de Visitantes (Código QR y Click Aprueba).' }, s2: { title: 'Área Interna y Externa', description: 'Seguridad Proactiva (Cámaras IA), Protección Perimetral (Cercas Virtuales), Visión Térmica.' }, s3: { title: 'Servicios y Gestión', description: 'Conectividad Total (Wi-Fi y Cat6), Automatización e IoT (Sensores de Fugas), Gestión Simplificada (Programación, Control de Entregas e Integración con ERP).' } },
      differentiator: { 
        title: 'Modernização Acessível:<br/>Tecnologia de Ponta sem Desembolso Inicial', 
        table: { 
          h1: 'Característica', 
          h2: 'Modelo Tradicional', 
          h3: 'Now Soluções', 
          r1: { feature: '<strong>Coste Inicial</strong>', traditional: 'Promedio de R$150,000 por adelantado', now: '<strong>R$0,00 - Inversión Cero</strong>' }, 
          r2: { feature: 'Mantenimiento y Suporte', traditional: 'Coste anual y por llamada', now: '<strong>Incluido e Ilimitado</strong>' }, 
          r3: { feature: 'Previsibilidad', traditional: 'Baja (Costos variables)', now: '<strong>Total</strong> - Valor Fijo Mensual' },
          r4: { feature: 'Assembleia', traditional: 'Necessária aprovação de 2/3 dos condôminos', now: '<strong>Aprovação simples</strong> (maioria simples)' },
          r5: { feature: 'Suporte Técnico', traditional: 'Atendimento em horário comercial', now: '<strong>24 horas por dia, 7 dias por semana</strong>' },
          r6: { feature: 'Actualizaciones y Garantía', traditional: 'Coste adicional, garantía limitada', now: '<strong>Incluida</strong> y garantizada durante todo el contrato' } 
        } 
      },
      finalCta: { title: 'Deje de Posponer la Seguridad y la Eficiencia de su Condominio.', subtitle: 'Dé el primer paso para tener un condominio más seguro, eficiente y valorado. Solicite ahora un análisis técnico y descubra el plan ideal para su realidad.', cta: 'Solicitar una Demostración o Estudio de Viabilidad Gratuito' }
    },
    metadata: { home: { title: 'Now Soluções | Más control, menos costos.', description: 'Now Soluções: Especialistas en tecnología para condominios inteligentes. Ofrecemos control de acceso, monitoreo con IA, casilleros inteligentes y más.', keywords: 'condominio inteligente, seguridad de condominios, control de acceso, portero remoto, now soluções' }, quemSomos: { title: 'Quiénes Somos | Now Soluções', description: 'Conozca la historia y los valores de Now Soluções, la empresa que está revolucionando la gestión de condominios con tecnología de punta y enfoque en el cliente.', keywords: 'sobre now soluções, historia, valores, equipo, gestión de condominios' }, contato: { title: 'Contacto | Now Soluções', description: 'Póngase en contacto con Now Soluções. Resuelva sus dudas, solicite un presupuesto o hable con nuestro equipo de especialistas en seguridad y tecnología para condominios.', keywords: 'contacto now soluções, teléfono, correo electrónico, dirección, presupuesto condominio' }, solucoes: { title: 'Nuestras Soluciones | Now Soluções', description: 'Descubra las soluciones de Now para áreas de acceso, áreas externas e internas, servicios y proyectos a medida para su condominio.', keywords: 'soluciones para condominios, área de acceso, monitoreo con ia, servicios, proyectos personalizados' }, areaAcesso: { title: 'Área de Acceso | Now Soluções', description: 'Soluciones de control de acceso vehicular, Código QR, biometría y reconocimiento facial para condominios.', keywords: 'control de acceso, rfid, código qr, biometría, conserjería' }, areaInterna: { title: 'Área Interna | Now Soluções', description: 'Monitoreo con cámaras de alta resolución, análisis de comportamiento y gestión de áreas comunes.', keywords: 'cámaras de seguridad, ia, reserva de áreas, sensores iot' }, areaExterna: { title: 'Área Externa | Now Soluções', description: 'Protección perimetral con cercas virtuales, lectura de matrículas (LPR) y visión térmica.', keywords: 'cerca virtual, lpr, lectura de matrícula, visión térmica, seguridad perimetral' }, facilities: { title: 'Servicios | Now Soluções', description: 'Optimice la gestión de servicios con Wi-Fi de alto rendimiento, switches y gestión de mantenimientos.', keywords: 'servicios, gestión de mantenimiento, wifi para condominios, switches' }, solucoesSobMedida: { title: 'Soluciones a Medida | Now Soluções', description: 'Proyectos personalizados de seguridad y tecnología para satisfacer las necesidades únicas de su condominio.', keywords: 'proyectos personalizados, seguridad de condominios, consultoría de seguridad' } }
    ,
    whatsappTooltip: 'Hable con un experto'
  },
  'zh-CN': {
    nav: { home: '首页', smartCondo: '智能公寓', solutions: '我们的解决方案', about: '关于我们', contact: '联系我们' },
    solutionsSub: { access: '门禁区域', external: '外部区域', internal: '内部区域', facilities: '设施管理', custom: '定制解决方案' },
    header: { cta: '请求报价' },
    hero: { slide1: { title: '人工智能<br/>摄像头', subtitle: '有了Now Soluções，您的公寓就拥有了能够识别移动、触发传感器和创建虚拟屏障的智能摄像头。更精确，更安全，更省心。' }, slide2: { title: '智能便捷<br/>门禁', subtitle: '面部识别、二维码和车辆识别。用最高科技为住户和访客提供安全与便利。' }, slide3: { title: '全面管理<br/>尽在掌中', subtitle: '我们的应用程序集中了所有功能，从访客授权到公共区域预订。高效透明的管理。' }, cta: '与专家交谈' },
    impact: { title: '我们的影响力', stat1: { value: '+80', label: '服务的公寓' }, stat2: { value: '+15', label: '年市场经验' }, stat3: { value: '+15k', label: '影响的居民' }, stat4: { value: '98%', label: '物业经理满意度' } },
    solutions: { title: '您的公寓更智能。您的生活更安全。', subtitle: '我们结合尖端技术、贴心的客户服务和个性化解决方案，改变住宅和商业公寓的日常生活。每项服务都旨在为物业经理、住户和管理人员提供更高的安全性、便利性和安心。', card1: { title: '智能门禁', description: '面部识别、二维码、数字邀请、车辆识别和通过应用程序远程开锁。' }, card2: { title: '人工智能监控', description: '带有人工智能的摄像头、虚拟围栏、声光报警器和行为分析传感器。' }, card3: { title: '智能储物柜', description: '24/7包裹接收，安全自主。通过应用程序通知取件。' } },
    about: { tagline: '我们的优势', title: '为什么选择Now？', description: '我们为每个公寓的实际情况提供量身定制的智能解决方案。我们陪伴物业经理和管理人员从诊断到运营的每一个阶段，提供专门的支持、尖端的技术，并完全专注于安全、效率和安心。', partnersTagline: '我们的合作伙伴' },
    cta: { title: '精益求精', description: '我们的承诺是提供真正有效的解决方案。凭借尖端的技术、专业的团队和持续的支持，我们提供安全、流畅、高效的公寓管理体验。', button: '与专家交谈' },
    testimonials: { title: '客户评价', t1: { quote: '有了Now，我们能够组织我们公寓的所有沟通和控制。这个应用程序让每个人的生活都变得轻松多了。', name: '卡洛斯·门德斯', title: '物业经理', company: 'Vila Serena公寓' }, t2: { quote: '面部识别门禁系统和智能储物柜彻底改变了我们的日常生活。我们现在更安全，更有条理。', name: '安娜·卢西亚·巴罗斯', title: '管理员', company: 'Smart Park Alphaville' }, t3: { quote: '敏捷高效的技术支持。Now团队随时准备为我们提供帮助，这在日常管理中至关重要。', name: '罗伯托·阿尔梅达', title: '经理', company: 'Corporate Tower大厦' } },
    footer: { description: 'Now Soluções - 我们连接安全、技术和管理，改变您的公寓。', nav: { home: '首页', about: '关于我们', contact: '联系我们', privacy: '隐私政策' }, solutions: { smartCondo: '智能公寓', access: '门禁区域', external: '外部区域', internal: '内部区域', facilities: '设施管理', custom: '定制解决方案' }, contact: { phone: '+55 (11) 5283-5040', address: 'Antônio Nápoli街229号<br/>圣保罗，SP<br/>02987-030, 巴西' }, copyright: '© Now Soluções | 版权所有 | 2025' },
    quemSomos: { hero: { title: '关于Now Soluções', subtitle: '连接技术、安全和人，创建更智能的公寓和更强大的社区。' }, story: { tagline: '我们的历程', title: '为创新而生', p1: 'Now Soluções成立的使命是彻底改变巴西的公寓管理。我们认识到技术可以成为物业经理和住户的强大盟友，为日常生活带来更多安全、效率和安心。从一开始，我们的重点就是开发和整合真正有用的解决方案。', p2: '凭借在技术和安全领域超过15年的综合经验，我们的团队致力于了解每个公寓的独特挑战，提供个性化服务和超越期望的支持。' }, values: { title: '我们的价值观', v1: { title: '创新', description: '我们不断寻求最先进的解决方案，以确保在安全和管理方面的技术领先地位。' }, v2: { title: '安全', description: '客户的保护是我们的最高优先事项，体现在我们提供的每一个产品和服务中。' }, v3: { title: '客户至上', description: '我们与物业经理和住户合作，以卓越的服务理解并满足他们的实际需求。' } }, partners: { title: '信任我们工作的公司' } },
    contato: { hero: { title: '联系我们', subtitle: '有任何问题或想请求报价吗？我们的团队随时准备提供帮助。' }, form: { title: '发送消息', subtitle: '请填写表格，我们会尽快与您联系。', name: '姓名', email: '电子邮件', subject: '主题', message: '消息', submit: '发送消息', loading: '发送中...', success: '消息发送成功！感谢您的联系。', error: '发送消息时发生错误。请再试一次。' }, info: { title: '我们的信息', address: { title: '地址', value: 'Antônio Nápoli街229号<br/>圣保罗，SP, 02987-030, 巴西' }, phone: { title: '电话', value: '+55 (11) 5283-5040' }, email: { title: '电子邮件', value: 'contato@nowsolucoes.com.br' } } },
    solucoesPage: { hero: { title: '我们的解决方案', subtitle: '技术与创新，改变您公寓的安全与管理。' }, s1: { title: '门禁区域', description: '完整的出入控制解决方案，包括面部识别、二维码、数字邀请和与远程门房的集成，以实现最大的安全性和便利性。' }, s2: { title: '外部区域', description: '使用高清摄像头进行周边监控，带有人工智能的虚拟围栏，声光报警器和运动传感器，以全面保护公寓。' }, s3: { title: '内部区域', description: '对健身房、派对室和游泳池等公共区域的访问控制。确保只有授权的住户才能使用这些空间，并通过应用程序提供使用报告和预订功能。' }, s4: { title: '设施管理', description: '通过照明自动化系统、水泵控制和预防性维护管理来优化设施管理，降低成本并提高效率。' }, s5: { title: '定制解决方案', description: '我们理解每个公寓都是独一无二的。我们开发定制项目，整合不同技术，以满足您特定的安全和管理需求。' } },
    areaAcessoPage: { hero: { title: '门禁区域', subtitle: '尖端技术，实现安全、敏捷、完全集成的门禁控制。' }, intro: { title: '入口处的安全与便利', description: '我们的门禁区域解决方案结合了最先进的技术，确保只有授权人员才能进入公寓。我们提供一个强大而灵活的系统，适应住户、访客和服务提供商的需求，所有这些都集中管理。' }, products: { p1: { title: '车辆控制（RFID标签）', description: '使用射频标签加快车辆进出。系统自动识别注册车辆，无需遥控器即可开门。' }, p2: { title: '二维码放行', description: '为访客生成带有唯一二维码的数字邀请。这是一种实用而安全的解决方案，无需使用对讲机，并在活动日加快门禁速度。' }, p3: { title: '生物识别和面部识别', description: '利用最新的生物识别和面部识别技术，为住户提供快速安全的门禁。精度高，无法伪造。' }, p4: { title: '门房平板电脑', description: '在直观的平板电脑上集中控制和登记访客及服务提供商。方便门房工作，并保留所有门禁的数字记录。' } } },
    areaInternaPage: { hero: { title: '内部区域', subtitle: '为您公寓的公共空间提供智能监控和管理。' }, intro: { title: '公寓内部的保护与效率', description: '通过我们的内部监控和管理解决方案，确保公共区域的安全和正常使用。从视频监控到预订自动化，我们提供的工具为住户的日常生活带来安心和秩序。' }, products: { p1: { title: '高清摄像头', description: '用高清摄像头监控走廊、电梯、车库和休闲区，确保图像清晰，保障大家的安全。' }, p2: { title: '人工智能行为分析', description: '我们的人工智能可检测可疑活动，如徘徊或异常行为，并实时警报监控中心。' }, p3: { title: '公共区域预订', description: '通过我们的应用程序管理派对室、烧烤区和球场的预订。对住户简单，对物业经理有条理。' }, p4: { title: '物联网传感器（水/气）', description: '检测关键区域的水或煤气泄漏并立即收到警报，防止事故和重大损失。' } } },
    areaExternaPage: { hero: { title: '外部区域', subtitle: '智能周边保护，保护您的公寓免受威胁。' }, intro: { title: '永不休眠的警戒', description: '公寓的安全始于其边界。我们的外部区域解决方案利用人工智能和尖端技术，创建坚固的保护屏障，在威胁靠近之前就将其检测出来。' }, products: { p1: { title: '入侵检测（虚拟围栏）', description: '在墙壁和周边创建虚拟屏障。任何入侵企图都会立即触发中央站的警报，从而实现快速响应。' }, p2: { title: '车牌自动识别（LPR）', description: '监控所有进出公寓的车辆。LPR系统记录并存储车牌，创建有价值的安全历史记录。' }, p3: { title: '热成像', description: '热像仪可在完全黑暗、大雾或雨中检测人员和车辆的存在，确保24/7有效监控。' } } },
    facilitiesPage: { hero: { title: '设施管理', subtitle: '利用技术和自动化优化资源和维护管理。' }, intro: { title: '智能管理，降低成本', description: '我们的设施解决方案有助于自动化任务、监控资源并主动管理公寓维护。结果是更高的运营效率、成本降低和设备更长的使用寿命。' }, products: { p1: { title: '高性能Wi-Fi', description: '在公寓的公共区域提供稳定、高速的互联网连接，并提供集中管理和访客接入门户。' }, p2: { title: '可管理交换机', description: '构建一个强大可靠的网络基础设施，以完全控制的方式支持公寓的所有安全和自动化系统。' }, p3: { title: '维护管理', description: '通过我们的系统安排和控制电梯、水泵和其他设备的预防性维护，并提供自动警报和报告。' }, p4: { title: 'ERP集成', description: '将我们的管理和门禁控制系统与管理员的ERP连接，实现流程自动化和信息集中化。' } } },
    solucoesSobMedidaPage: { hero: { title: '定制解决方案', subtitle: '您的公寓是独一无二的。您的安全解决方案也应如此。' }, intro: { title: '我们为您打造理想项目', description: '我们理解没有一刀切的解决方案。我们的专家团队随时准备分析您公寓的具体需求，并设计一个完全定制的安全和技术项目。我们结合不同的技术，创建一个集成、高效且符合您预算的系统。' }, form: { title: '与专家交谈', subtitle: '请填写下面的表格，我们的一位顾问将与您联系，安排一次对话，了解您的挑战。' } },
    condominioInteligentePage: {
      hero: { title: '现代化、安全与智能：您公寓的未来始于现在。', subtitle: '尖端技术，初始投资为零。按月订阅解决方案，确保您的财产安全和增值。', cta: '为您的公寓申请免费分析' },
      socialProof1: { title: '信任 NOW 的客户' },
      challenge: { title: '在不影响现金流的情况下实现现代化的挑战', c1: { title: '脆弱的安全性', description: '传统的监控系统只能事后反应，无法预防。' }, c2: { title: '繁琐的门禁', description: '排队、登记失败以及入口处的漏洞。' }, c3: { title: '低效的管理', description: '手动流程消耗了物业经理和管理员的时间。' } },
      solution: { 
        title: 'Conheça os 4 Pilares do Condomínio Inteligente Now', 
        p1: { icon: 'security', title: '带有人工智能的智能安防', description: '能够预测和预防事故的主动系统，提供24/7监控。' }, 
        p2: { icon: 'wifi', title: '高性能连接', description: '在所有公共区域提供稳定、高速的互联网。' }, 
        p3: { icon: 'devices', title: '数字化管理与自动化', description: '优化物业经理和住户的日常工作。' },
        p4: { icon: 'key', title: '高级门禁控制', description: '为住户和访客提供最大程度的便利和安全。' }
      },
      socialProof: { 
        title: 'Case de Sucesso', 
        subtitle: '观看客户评价，了解 Condomínio Stilize 如何使用 NOW 实现现代化，并实现零实施成本。', 
        cta: '了解 Stilize 项目可行的财务模型。' 
      },
      detailedSolutions: { title: 'Tecnologia em Cada Canto do seu Condomínio', s1: { title: '门禁区域', description: '车辆控制（RFID和LPR标签）、行人门禁（面部和生物识别）、访客管理（二维码和点击批准）。' }, s2: { title: '内部和外部区域', description: '主动安防（AI摄像头）、周边保护（虚拟围栏）、热成像。' }, s3: { title: '设施与管理', description: '全面连接（Wi-Fi和Cat6）、自动化与物联网（泄漏传感器）、简化管理（预订、包裹控制和ERP集成）。' } },
      differentiator: { 
        title: 'Modernização Acessível:<br/>Tecnologia de Ponta sem Desembolso Inicial', 
        table: { 
          h1: '功能', 
          h2: '传统模式', 
          h3: 'Now Soluções', 
          r1: { feature: '<strong>初始成本</strong>', traditional: '平均预付150,000雷亚尔', now: '<strong>0.00雷亚尔 - 零投资</strong>' }, 
          r2: { feature: '维护与支持', traditional: '年费和按次收费', now: '<strong>包含且无限制</strong>' }, 
          r3: { feature: '可预测性', traditional: '低（可变成本）', now: '<strong>完全</strong> - 固定月费' },
          r4: { feature: 'Assembleia', traditional: 'Necessária aprovação de 2/3 dos condôminos', now: '<strong>Aprovação simples</strong> (maioria simples)' },
          r5: { feature: 'Suporte Técnico', traditional: 'Atendimento em horário comercial', now: '<strong>24 horas por dia, 7 dias por semana</strong>' },
          r6: { feature: '更新与保修', traditional: '额外费用，有限保修', now: '<strong>包含</strong>并在整个合同期内提供保障' } 
        } 
      },
      finalCta: { title: '不要再推迟您公寓的安全与效率。', subtitle: '迈出第一步，拥有一个更安全、更高效、更有价值的公寓。立即申请技术分析，发现适合您实际情况的理想方案。', cta: '申请免费演示或可行性研究' }
    },
    whatsappTooltip: '与专家交谈'
  }
};

export default translations;