const translations = {
  'pt-BR': {
    nav: {
      home: 'Home',
      smartCondo: 'Condomínio inteligente',
      solutions: 'Nossas Soluções',
      about: 'Quem Somos',
      contact: 'Contato',
    },
    solutionsSub: {
      access: 'Área de Acesso',
      external: 'Área Externa',
      internal: 'Área Interna',
      facilities: 'Facilities',
      custom: 'Soluções sob medida',
    },
    header: {
      cta: 'Pedir Orçamento',
    },
    hero: {
      slide1: {
        title: 'Câmeras com inteligência<br/>artificial',
        subtitle: 'Com a Now Soluções, seu condomínio conta com câmeras inteligentes que identificam movimentações, acionam sensores e criam barreiras virtuais. Mais precisão, mais proteção, menos preocupações.'
      },
      slide2: {
        title: 'Acesso Inteligente<br/>e Descomplicado',
        subtitle: 'Controle facial, QR Code e reconhecimento veicular. Ofereça segurança e praticidade para moradores e visitantes com a mais alta tecnologia.'
      },
      slide3: {
        title: 'Gestão Completa<br/>na Palma da Mão',
        subtitle: 'Nosso aplicativo centraliza todas as funcionalidades, desde a liberação de visitantes até a reserva de áreas comuns. Gestão eficiente e transparente.'
      },
      cta: 'Fale com um especialista',
    },
    impact: {
      title: 'Nosso Impacto',
      stat1: { value: '+80', label: 'Condomínios atendidos' },
      stat2: { value: '+15', label: 'Anos de Experiência de Mercado' },
      stat3: { value: '+15k', label: 'Moradores Impactados' },
      stat4: { value: '98%', label: 'Satisfação entre síndicos' }
    },
    solutions: {
      title: 'Seu condomínio mais inteligente. Sua vida mais segura.',
      subtitle: 'Combinamos tecnologia de ponta, atendimento próximo e soluções personalizadas para transformar a rotina de condomínios residenciais e comerciais. Cada serviço é desenvolvido para oferecer mais segurança, praticidade e tranquilidade para síndicos, moradores e administradoras.',
      card1: { title: 'Acesso Inteligente', description: 'Controle facial, QR Code, convites digitais, reconhecimento veicular e liberação remota via app.' },
      card2: { title: 'Monitoramento IA', description: 'Câmeras com inteligência artificial, cercas virtuais, alarmes sonoros e sensores com análise de comportamento.' },
      card3: { title: 'Armários Inteligentes', description: 'Recebimento de encomendas 24/7 com segurança e autonomia. Notificações via app para retirada.' },
    },
    about: {
      tagline: 'DIFERENCIAIS',
      title: 'Por que escolher a Now?',
      description: 'Temos a solução inteligente e sob medida para a realidade de cada condomínio. Acompanhamos síndicos e gestores em todas as etapas, desde o diagnóstico até a operação, com suporte dedicado, tecnologia de ponta e foco total em segurança, eficiência e tranquilidade.',
      partnersTagline: 'NOSSOS PARCEIROS',
    },
    cta: {
      title: 'Excelência em cada detalhe',
      description: 'Nosso compromisso é entregar soluções que funcionam de verdade. Com tecnologia de ponta, equipe especializada e suporte contínuo, oferecemos uma experiência de gestão condominial segura, fluida e eficiente.',
      button: 'Fale com um especialista'
    },
    testimonials: {
      title: 'O que nossos clientes dizem',
      t1: { quote: 'Com a Now conseguimos organizar toda a comunicação e controle do nosso condomínio. O aplicativo facilitou muito a vida de todos.', name: 'Carlos Mendes', title: 'síndico', company: 'Condomínio Vila Serena' },
      t2: { quote: 'O sistema de acesso facial e os armários inteligentes mudaram completamente nossa rotina. Estamos mais seguros e organizados.', name: 'Ana Lúcia Barros', title: 'gestora', company: 'Smart Park Alphaville' },
      t3: { quote: 'Suporte técnico ágil e eficiente. A equipe da Now está sempre pronta para nos atender, o que faz toda a diferença na gestão diária.', name: 'Roberto Almeida', title: 'administrador', company: 'Edifício Corporate Tower' },
    },
    footer: {
      description: 'Now Soluções - Conectamos segurança, tecnologia e gestão para transformar seu condomínio.',
      nav: { home: 'Home', about: 'Quem Somos', contact: 'Contato', privacy: 'Política de Privacidade' },
      solutions: { smartCondo: 'Condomínio Inteligente', access: 'Área de Acesso', external: 'Área Externa', internal: 'Área Interna', facilities: 'Facilities', custom: 'Soluções sob Medida' },
      contact: { phone: '(11) 5283-5040', address: 'Rua Antônio Nápoli, 229<br/>Parada São Paulo - SP<br/>02987-030' },
      copyright: '© Now Soluções | Todos os direitos reservados | 2025'
    },
    quemSomos: {
      hero: { title: 'Sobre a Now Soluções', subtitle: 'Conectando tecnologia, segurança e pessoas para criar condomínios mais inteligentes e comunidades mais fortes.' },
      story: { tagline: 'NOSSA JORNADA', title: 'Nascemos para inovar', p1: 'A Now Soluções foi fundada com a missão de revolucionar a gestão condominial no Brasil. Percebemos que a tecnologia poderia ser uma aliada poderosa para síndicos e moradores, trazendo mais segurança, eficiência e tranquilidade para o dia a dia. Desde o início, nosso foco tem sido desenvolver e integrar soluções que realmente fazem a diferença.', p2: 'Com mais de 15 anos de experiência combinada no setor de tecnologia e segurança, nossa equipe se dedica a entender os desafios únicos de cada condomínio, oferecendo um serviço personalizado e um suporte que vai além do esperado.' },
      values: { title: 'Nossos Valores', v1: { title: 'Inovação', description: 'Buscamos constantemente as soluções mais avançadas para garantir a vanguarda tecnológica em segurança e gestão.' }, v2: { title: 'Segurança', description: 'A proteção dos nossos clientes é a nossa prioridade máxima, refletida em cada produto e serviço que oferecemos.' }, v3: { title: 'Foco no Cliente', description: 'Trabalhamos em parceria com síndicos e moradores para entender e atender suas necessidades reais com excelência.' } },
      partners: { title: 'Empresas que confiam em nosso trabalho' }
    },
    contato: {
      hero: { title: 'Fale Conosco', subtitle: 'Tem alguma dúvida ou quer solicitar um orçamento? Nossa equipe está pronta para ajudar.' },
      form: { title: 'Envie uma mensagem', subtitle: 'Preencha o formulário e entraremos em contato o mais breve possível.', name: 'Nome', email: 'Email', subject: 'Assunto', message: 'Mensagem', submit: 'Enviar Mensagem', loading: 'Enviando...', success: 'Mensagem enviada com sucesso! Agradecemos o seu contato.', error: 'Ocorreu um erro ao enviar a mensagem. Por favor, tente novamente.' },
      info: { title: 'Nossas Informações', address: { title: 'Endereço', value: 'Rua Antônio Nápoli, 229<br/>Parada São Paulo - SP, 02987-030' }, phone: { title: 'Telefone', value: '(11) 5283-5040' }, email: { title: 'Email', value: 'contato@nowsolucoes.com.br' } }
    },
    solucoesPage: {
      hero: { title: 'Nossas Soluções', subtitle: 'Tecnologia e inovação para transformar a segurança e a gestão do seu condomínio.' },
      s1: { title: 'Área de Acesso', description: 'Soluções completas para controle de entrada e saída, incluindo reconhecimento facial, QR Code, convites digitais e integração com portaria remota para máxima segurança e conveniência.' },
      s2: { title: 'Área Externa', description: 'Monitoramento perimetral com câmeras de alta definição, cercas virtuais com inteligência artificial, alarmes sonoros e sensores de movimento para proteger o condomínio de ponta a ponta.' },
      s3: { title: 'Área Interna', description: 'Controle de acesso para áreas comuns como academias, salões de festas e piscinas. Garanta que apenas moradores autorizados utilizem os espaços, com relatórios de uso e agendamento via app.' },
      s4: { title: 'Facilities', description: 'Otimização da gestão de facilities com sistemas de automação para iluminação, controle de bombas de água e gerenciamento de manutenções preventivas, reduzindo custos e aumentando a eficiência.' },
      s5: { title: 'Soluções sob medida', description: 'Entendemos que cada condomínio é único. Desenvolvemos projetos personalizados que integram diferentes tecnologias para atender às suas necessidades específicas de segurança e gestão.' },
    },
    metadata: {
      home: { title: 'Now Soluções | Mais controle, menos custos.', description: 'Now Soluções: Especialistas em tecnologia para condomínios inteligentes. Oferecemos controle de acesso, monitoramento com IA, armários inteligentes e mais.', keywords: 'condomínio inteligente, segurança condominial, controle de acesso, portaria remota, now soluções' },
      quemSomos: { title: 'Sobre Nós | Now Soluções', description: 'Conheça a história e os valores da Now Soluções, a empresa que está revolucionando a gestão de condomínios com tecnologia de ponta e foco no cliente.', keywords: 'sobre now soluções, história, valores, equipe, gestão condominial' },
      contato: { title: 'Contato | Now Soluções', description: 'Entre em contato com a Now Soluções. Tire suas dúvidas, solicite um orçamento ou fale com nossa equipe de especialistas em segurança e tecnologia para condomínios.', keywords: 'contato now soluções, telefone, email, endereço, orçamento condomínio' },
      solucoes: { title: 'Nossas Soluções | Now Soluções', description: 'Descubra as soluções da Now para áreas de acesso, áreas externas, internas, facilities e projetos sob medida para o seu condomínio.', keywords: 'soluções condominiais, área de acesso, monitoramento ia, facilities, projetos personalizados' }
    },
    whatsappTooltip: 'Fale com um especialista'
  },
  'en-US': {
    nav: { home: 'Home', smartCondo: 'Smart Condominium', solutions: 'Our Solutions', about: 'About Us', contact: 'Contact' },
    solutionsSub: { access: 'Access Area', external: 'External Area', internal: 'Internal Area', facilities: 'Facilities', custom: 'Custom Solutions' },
    header: { cta: 'Request a Quote' },
    hero: { slide1: { title: 'Cameras with Artificial<br/>Intelligence', subtitle: 'With Now Soluções, your condominium has smart cameras that identify movements, trigger sensors, and create virtual barriers. More precision, more protection, less worry.' }, slide2: { title: 'Smart and Uncomplicated<br/>Access', subtitle: 'Facial recognition, QR Code, and vehicle recognition. Offer security and convenience for residents and visitors with the highest technology.' }, slide3: { title: 'Complete Management<br/>in Your Palm', subtitle: 'Our application centralizes all functionalities, from visitor authorization to booking common areas. Efficient and transparent management.' }, cta: 'Speak with an expert' },
    impact: { title: 'Our Impact', stat1: { value: '+80', label: 'Condominiums served' }, stat2: { value: '+15', label: 'Years of Market Experience' }, stat3: { value: '+15k', label: 'Residents Impacted' }, stat4: { value: '98%', label: 'Satisfaction among managers' } },
    solutions: { title: 'Your condominium smarter. Your life safer.', subtitle: 'We combine cutting-edge technology, close customer service, and personalized solutions to transform the routine of residential and commercial condominiums. Each service is developed to offer more security, convenience, and peace of mind for managers, residents, and administrators.', card1: { title: 'Smart Access', description: 'Facial recognition, QR Code, digital invitations, vehicle recognition, and remote release via app.' }, card2: { title: 'AI Monitoring', description: 'Cameras with artificial intelligence, virtual fences, sound alarms, and sensors with behavior analysis.' }, card3: { title: 'Smart Lockers', description: '24/7 package receiving with security and autonomy. Notifications via app for pickup.' } },
    about: { tagline: 'DIFFERENTIALS', title: 'Why choose Now?', description: 'We have the smart, tailor-made solution for the reality of each condominium. We accompany managers and administrators at every stage, from diagnosis to operation, with dedicated support, cutting-edge technology, and a total focus on security, efficiency, and peace of mind.', partnersTagline: 'OUR PARTNERS' },
    cta: { title: 'Excellence in every detail', description: 'Our commitment is to deliver solutions that truly work. With cutting-edge technology, a specialized team, and continuous support, we offer a secure, fluid, and efficient condominium management experience.', button: 'Speak with an expert' },
    testimonials: { title: "What our clients say", t1: { quote: 'With Now, we were able to organize all communication and control of our condominium. The app has made life much easier for everyone.', name: 'Carlos Mendes', title: 'manager', company: 'Vila Serena Condominium' }, t2: { quote: 'The facial access system and smart lockers have completely changed our routine. We are safer and more organized.', name: 'Ana Lúcia Barros', title: 'administrator', company: 'Smart Park Alphaville' }, t3: { quote: 'Agile and efficient technical support. The Now team is always ready to assist us, which makes all the difference in daily management.', name: 'Roberto Almeida', title: 'manager', company: 'Corporate Tower Building' } },
    footer: { description: 'Now Soluções - We connect security, technology, and management to transform your condominium.', nav: { home: 'Home', about: 'About Us', contact: 'Contact', privacy: 'Privacy Policy' }, solutions: { smartCondo: 'Smart Condominium', access: 'Access Area', external: 'External Area', internal: 'Internal Area', facilities: 'Facilities', custom: 'Custom Solutions' }, contact: { phone: '+55 (11) 5283-5040', address: 'Antônio Nápoli St, 229<br/>Parada São Paulo - SP<br/>02987-030, Brazil' }, copyright: '© Now Soluções | All rights reserved | 2025' },
    quemSomos: { hero: { title: 'About Now Soluções', subtitle: 'Connecting technology, security, and people to create smarter condominiums and stronger communities.' }, story: { tagline: 'OUR JOURNEY', title: 'Born to innovate', p1: 'Now Soluções was founded with the mission to revolutionize condominium management in Brazil. We realized that technology could be a powerful ally for managers and residents, bringing more security, efficiency, and peace of mind to daily life. From the beginning, our focus has been to develop and integrate solutions that truly make a difference.', p2: 'With over 15 years of combined experience in the technology and security sector, our team is dedicated to understanding the unique challenges of each condominium, offering personalized service and support that goes beyond expectations.' }, values: { title: 'Our Values', v1: { title: 'Innovation', description: 'We constantly seek the most advanced solutions to ensure the technological forefront in security and management.' }, v2: { title: 'Security', description: "Our clients' protection is our highest priority, reflected in every product and service we offer." }, v3: { title: 'Customer Focus', description: 'We work in partnership with managers and residents to understand and meet their real needs with excellence.' } }, partners: { title: 'Companies that trust our work' } },
    contato: { hero: { title: 'Contact Us', subtitle: 'Have a question or want to request a quote? Our team is ready to help.' }, form: { title: 'Send a message', subtitle: 'Fill out the form, and we will get in touch as soon as possible.', name: 'Name', email: 'Email', subject: 'Subject', message: 'Message', submit: 'Send Message', loading: 'Sending...', success: 'Message sent successfully! Thank you for your contact.', error: 'An error occurred while sending the message. Please try again.' }, info: { title: 'Our Information', address: { title: 'Address', value: 'Antônio Nápoli St, 229<br/>Parada São Paulo - SP, 02987-030, Brazil' }, phone: { title: 'Phone', value: '+55 (11) 5283-5040' }, email: { title: 'Email', value: 'contato@nowsolucoes.com.br' } } },
    solucoesPage: { hero: { title: 'Our Solutions', subtitle: 'Technology and innovation to transform the security and management of your condominium.' }, s1: { title: 'Access Area', description: 'Complete solutions for entry and exit control, including facial recognition, QR Code, digital invitations, and integration with remote concierge for maximum security and convenience.' }, s2: { title: 'External Area', description: 'Perimeter monitoring with high-definition cameras, virtual fences with artificial intelligence, sound alarms, and motion sensors to protect the condominium from end to end.' }, s3: { title: 'Internal Area', description: 'Access control for common areas such as gyms, party rooms, and pools. Ensure that only authorized residents use the spaces, with usage reports and scheduling via the app.' }, s4: { title: 'Facilities', description: 'Optimization of facilities management with automation systems for lighting, water pump control, and preventive maintenance management, reducing costs and increasing efficiency.' }, s5: { title: 'Custom Solutions', description: 'We understand that each condominium is unique. We develop customized projects that integrate different technologies to meet your specific security and management needs.' } },
    metadata: { home: { title: 'Now Soluções | More control, less costs.', description: 'Now Soluções: Specialists in smart condominium technology. We offer access control, AI monitoring, smart lockers, and more.', keywords: 'smart condominium, condo security, access control, remote doorman, now soluções' }, quemSomos: { title: 'About Us | Now Soluções', description: 'Learn about the history and values of Now Soluções, the company revolutionizing condominium management with cutting-edge technology and customer focus.', keywords: 'about now soluções, history, values, team, condominium management' }, contato: { title: 'Contact | Now Soluções', description: 'Get in touch with Now Soluções. Ask questions, request a quote, or speak with our team of specialists in security and technology for condominiums.', keywords: 'contact now soluções, phone, email, address, condo quote' }, solucoes: { title: 'Our Solutions | Now Soluções', description: 'Discover Now’s solutions for access areas, external and internal areas, facilities, and custom projects for your condominium.', keywords: 'condo solutions, access area, AI monitoring, facilities, custom projects' } },
    whatsappTooltip: 'Speak with an expert'
  },
  'es-ES': {
    nav: { home: 'Inicio', smartCondo: 'Condominio inteligente', solutions: 'Nuestras Soluciones', about: 'Quiénes Somos', contact: 'Contacto' },
    solutionsSub: { access: 'Área de Acceso', external: 'Área Externa', internal: 'Área Interna', facilities: 'Servicios', custom: 'Soluciones a Medida' },
    header: { cta: 'Solicitar Presupuesto' },
    hero: { slide1: { title: 'Cámaras con inteligencia<br/>artificial', subtitle: 'Con Now Soluções, su condominio cuenta con cámaras inteligentes que identifican movimientos, activan sensores y crean barreras virtuales. Más precisión, más protección, menos preocupaciones.' }, slide2: { title: 'Acceso Inteligente<br/>y Sencillo', subtitle: 'Control facial, Código QR y reconocimiento de vehículos. Ofrezca seguridad y practicidad a residentes y visitantes con la más alta tecnología.' }, slide3: { title: 'Gestión Completa<br/>en la Palma de la Mano', subtitle: 'Nuestra aplicación centraliza todas las funcionalidades, desde la autorización de visitantes hasta la reserva de áreas comunes. Gestión eficiente y transparente.' }, cta: 'Hable con un experto' },
    impact: { title: 'Nuestro Impacto', stat1: { value: '+80', label: 'Condominios atendidos' }, stat2: { value: '+15', label: 'Años de Experiencia en el Mercado' }, stat3: { value: '+15k', label: 'Residentes Impactados' }, stat4: { value: '98%', label: 'Satisfacción entre administradores' } },
    solutions: { title: 'Su condominio más inteligente. Su vida más segura.', subtitle: 'Combinamos tecnología de punta, atención cercana y soluciones personalizadas para transformar la rutina de condominios residenciales y comerciales. Cada servicio está desarrollado para ofrecer más seguridad, practicidad y tranquilidad a administradores, residentes y gestores.', card1: { title: 'Acceso Inteligente', description: 'Control facial, Código QR, invitaciones digitales, reconocimiento de vehículos y liberación remota vía app.' }, card2: { title: 'Monitoreo con IA', description: 'Cámaras con inteligencia artificial, cercas virtuales, alarmas sonoras y sensores con análisis de comportamiento.' }, card3: { title: 'Casilleros Inteligentes', description: 'Recepción de paquetes 24/7 con seguridad y autonomía. Notificaciones vía app para su recogida.' } },
    about: { tagline: 'DIFERENCIALES', title: '¿Por qué elegir Now?', description: 'Tenemos la solución inteligente y a medida para la realidad de cada condominio. Acompañamos a los administradores y gestores en todas las etapas, desde el diagnóstico hasta la operación, con soporte dedicado, tecnología de punta y un enfoque total en seguridad, eficiencia y tranquilidad.', partnersTagline: 'NUESTROS SOCIOS' },
    cta: { title: 'Excelencia en cada detalle', description: 'Nuestro compromiso es entregar soluciones que realmente funcionan. Con tecnología de punta, un equipo especializado y soporte continuo, ofrecemos una experiencia de gestión de condominios segura, fluida y eficiente.', button: 'Hable con un experto' },
    testimonials: { title: 'Lo que dicen nuestros clientes', t1: { quote: 'Con Now logramos organizar toda la comunicación y control de nuestro condominio. La aplicación facilitó mucho la vida de todos.', name: 'Carlos Mendes', title: 'administrador', company: 'Condominio Vila Serena' }, t2: { quote: 'El sistema de acceso facial y los casilleros inteligentes cambiaron por completo nuestra rutina. Estamos más seguros y organizados.', name: 'Ana Lúcia Barros', title: 'gestora', company: 'Smart Park Alphaville' }, t3: { quote: 'Soporte técnico ágil y eficiente. El equipo de Now siempre está listo para atendernos, lo que marca toda la diferencia en la gestión diaria.', name: 'Roberto Almeida', title: 'administrador', company: 'Edificio Corporate Tower' } },
    footer: { description: 'Now Soluções - Conectamos seguridad, tecnología y gestión para transformar su condominio.', nav: { home: 'Inicio', about: 'Quiénes Somos', contact: 'Contacto', privacy: 'Política de Privacidad' }, solutions: { smartCondo: 'Condominio Inteligente', access: 'Área de Acceso', external: 'Área Externa', internal: 'Área Interna', facilities: 'Servicios', custom: 'Soluciones a Medida' }, contact: { phone: '+55 (11) 5283-5040', address: 'Calle Antônio Nápoli, 229<br/>Parada São Paulo - SP<br/>02987-030, Brasil' }, copyright: '© Now Soluções | Todos los derechos reservados | 2025' },
    quemSomos: { hero: { title: 'Sobre Now Soluções', subtitle: 'Conectando tecnología, seguridad y personas para crear condominios más inteligentes y comunidades más fuertes.' }, story: { tagline: 'NUESTRA TRAYECTORIA', title: 'Nacimos para innovar', p1: 'Now Soluções fue fundada con la misión de revolucionar la gestión de condominios en Brasil. Nos dimos cuenta de que la tecnología podría ser un poderoso aliado para administradores y residentes, aportando más seguridad, eficiencia y tranquilidad al día a día. Desde el principio, nuestro enfoque ha sido desarrollar e integrar soluciones que realmente marcan la diferencia.', p2: 'Con más de 15 años de experiencia combinada en el sector de la tecnología y la seguridad, nuestro equipo se dedica a comprender los desafíos únicos de cada condominio, ofreciendo un servicio personalizado y un soporte que supera las expectativas.' }, values: { title: 'Nuestros Valores', v1: { title: 'Innovación', description: 'Buscamos constantemente las soluciones más avanzadas para garantizar la vanguardia tecnológica en seguridad y gestión.' }, v2: { title: 'Seguridad', description: 'La protección de nuestros clientes es nuestra máxima prioridad, reflejada en cada producto y servicio que ofrecemos.' }, v3: { title: 'Enfoque en el Cliente', description: 'Trabajamos en colaboración con administradores y residentes para comprender y satisfacer sus necesidades reales con excelencia.' } }, partners: { title: 'Empresas que confían en nuestro trabajo' } },
    contato: { hero: { title: 'Contáctenos', subtitle: '¿Tiene alguna pregunta o desea solicitar un presupuesto? Nuestro equipo está listo para ayudar.' }, form: { title: 'Envíe un mensaje', subtitle: 'Complete el formulario y nos pondremos en contacto lo antes posible.', name: 'Nombre', email: 'Correo Electrónico', subject: 'Asunto', message: 'Mensaje', submit: 'Enviar Mensaje', loading: 'Enviando...', success: '¡Mensaje enviado con éxito! Gracias por su contacto.', error: 'Ocurrió un error al enviar el mensaje. Por favor, inténtelo de nuevo.' }, info: { title: 'Nuestra Información', address: { title: 'Dirección', value: 'Calle Antônio Nápoli, 229<br/>Parada São Paulo - SP, 02987-030, Brasil' }, phone: { title: 'Teléfono', value: '+55 (11) 5283-5040' }, email: { title: 'Correo Electrónico', value: 'contato@nowsolucoes.com.br' } } },
    solucoesPage: { hero: { title: 'Nuestras Soluciones', subtitle: 'Tecnología e innovación para transformar la seguridad y la gestión de su condominio.' }, s1: { title: 'Área de Acceso', description: 'Soluciones completas para control de entrada y salida, incluyendo reconocimiento facial, Código QR, invitaciones digitales e integración con conserjería remota para máxima seguridad y comodidad.' }, s2: { title: 'Área Externa', description: 'Monitoreo perimetral con cámaras de alta definición, cercas virtuales con inteligencia artificial, alarmas sonoras y sensores de movimiento para proteger el condominio de extremo a extremo.' }, s3: { title: 'Área Interna', description: 'Control de acceso para áreas comunes como gimnasios, salones de fiestas y piscinas. Asegúrese de que solo los residentes autorizados utilicen los espacios, con informes de uso y programación a través de la aplicación.' }, s4: { title: 'Servicios', description: 'Optimización de la gestión de servicios con sistemas de automatización para iluminación, control de bombas de agua y gestión de mantenimiento preventivo, reduciendo costos y aumentando la eficiencia.' }, s5: { title: 'Soluciones a Medida', description: 'Entendemos que cada condominio es único. Desarrollamos proyectos personalizados que integran diferentes tecnologías para satisfacer sus necesidades específicas de seguridad y gestión.' } },
    metadata: { home: { title: 'Now Soluções | Más control, menos costos.', description: 'Now Soluções: Especialistas en tecnología para condominios inteligentes. Ofrecemos control de acceso, monitoreo con IA, casilleros inteligentes y más.', keywords: 'condominio inteligente, seguridad de condominios, control de acceso, portero remoto, now soluções' }, quemSomos: { title: 'Quiénes Somos | Now Soluções', description: 'Conozca la historia y los valores de Now Soluções, la empresa que está revolucionando la gestión de condominios con tecnología de punta y enfoque en el cliente.', keywords: 'sobre now soluções, historia, valores, equipo, gestión de condominios' }, contato: { title: 'Contacto | Now Soluções', description: 'Póngase en contacto con Now Soluções. Resuelva sus dudas, solicite un presupuesto o hable con nuestro equipo de especialistas en seguridad y tecnología para condominios.', keywords: 'contacto now soluções, teléfono, correo electrónico, dirección, presupuesto condominio' }, solucoes: { title: 'Nuestras Soluciones | Now Soluções', description: 'Descubra las soluciones de Now para áreas de acceso, áreas externas e internas, servicios y proyectos a medida para su condominio.', keywords: 'soluciones para condominios, área de acceso, monitoreo con ia, servicios, proyectos personalizados' } },
    whatsappTooltip: 'Hable con un experto'
  },
  'zh-CN': {
    nav: { home: '首页', smartCondo: '智能公寓', solutions: '我们的解决方案', about: '关于我们', contact: '联系我们' },
    solutionsSub: { access: '门禁区域', external: '外部区域', internal: '内部区域', facilities: '设施管理', custom: '定制解决方案' },
    header: { cta: '请求报价' },
    hero: { slide1: { title: '人工智能<br/>摄像头', subtitle: '有了Now Soluções，您的公寓就拥有了能够识别移动、触发传感器和创建虚拟屏障的智能摄像头。更精确，更安全，更省心。' }, slide2: { title: '智能便捷<br/>门禁', subtitle: '面部识别、二维码和车辆识别。用最高科技为住户和访客提供安全与便利。' }, slide3: { title: '全面管理<br/>尽在掌中', subtitle: '我们的应用程序集中了所有功能，从访客授权到公共区域预订。高效透明的管理。' }, cta: '与专家交谈' },
    impact: { title: '我们的影响力', stat1: { value: '+80', label: '服务的公寓' }, stat2: { value: '+15', label: '年市场经验' }, stat3: { value: '+15k', label: '影响的居民' }, stat4: { value: '98%', label: '物业经理满意度' } },
    solutions: { title: '您的公寓更智能。您的生活更安全。', subtitle: '我们结合尖端技术、贴心的客户服务和个性化解决方案，改变住宅和商业公寓的日常生活。每项服务都旨在为物业经理、住户和管理人员提供更高的安全性、便利性和安心。', card1: { title: '智能门禁', description: '面部识别、二维码、数字邀请、车辆识别和通过应用程序远程开锁。' }, card2: { title: '人工智能监控', description: '带有人工智能的摄像头、虚拟围栏、声光报警器和行为分析传感器。' }, card3: { title: '智能储物柜', description: '24/7包裹接收，安全自主。通过应用程序通知取件。' } },
    about: { tagline: '我们的优势', title: '为什么选择Now？', description: '我们为每个公寓的实际情况提供量身定制的智能解决方案。我们陪伴物业经理和管理人员从诊断到运营的每一个阶段，提供专门的支持、尖端的技术，并完全专注于安全、效率和安心。', partnersTagline: '我们的合作伙伴' },
    cta: { title: '精益求精', description: '我们的承诺是提供真正有效的解决方案。凭借尖端的技术、专业的团队和持续的支持，我们提供安全、流畅、高效的公寓管理体验。', button: '与专家交谈' },
    testimonials: { title: '客户评价', t1: { quote: '有了Now，我们能够组织我们公寓的所有沟通和控制。这个应用程序让每个人的生活都变得轻松多了。', name: '卡洛斯·门德斯', title: '物业经理', company: 'Vila Serena公寓' }, t2: { quote: '面部识别门禁系统和智能储物柜彻底改变了我们的日常生活。我们现在更安全，更有条理。', name: '安娜·卢西亚·巴罗斯', title: '管理员', company: 'Smart Park Alphaville' }, t3: { quote: '敏捷高效的技术支持。Now团队随时准备为我们提供帮助，这在日常管理中至关重要。', name: '罗伯托·阿尔梅达', title: '经理', company: 'Corporate Tower大厦' } },
    footer: { description: 'Now Soluções - 我们连接安全、技术和管理，改变您的公寓。', nav: { home: '首页', about: '关于我们', contact: '联系我们', privacy: '隐私政策' }, solutions: { smartCondo: '智能公寓', access: '门禁区域', external: '外部区域', internal: '内部区域', facilities: '设施管理', custom: '定制解决方案' }, contact: { phone: '+55 (11) 5283-5040', address: 'Antônio Nápoli街229号<br/>圣保罗，SP<br/>02987-030, 巴西' }, copyright: '© Now Soluções | 版权所有 | 2025' },
    quemSomos: { hero: { title: '关于Now Soluções', subtitle: '连接技术、安全和人，创建更智能的公寓和更强大的社区。' }, story: { tagline: '我们的历程', title: '为创新而生', p1: 'Now Soluções成立的使命是彻底改变巴西的公寓管理。我们认识到技术可以成为物业经理和住户的强大盟友，为日常生活带来更多安全、效率和安心。从一开始，我们的重点就是开发和整合真正有用的解决方案。', p2: '凭借在技术和安全领域超过15年的综合经验，我们的团队致力于了解每个公寓的独特挑战，提供个性化服务和超越期望的支持。' }, values: { title: '我们的价值观', v1: { title: '创新', description: '我们不断寻求最先进的解决方案，以确保在安全和管理方面的技术领先地位。' }, v2: { title: '安全', description: '客户的保护是我们的最高优先事项，体现在我们提供的每一个产品和服务中。' }, v3: { title: '客户至上', description: '我们与物业经理和住户合作，以卓越的服务理解并满足他们的实际需求。' } }, partners: { title: '信任我们工作的公司' } },
    contato: { hero: { title: '联系我们', subtitle: '有任何问题或想请求报价吗？我们的团队随时准备提供帮助。' }, form: { title: '发送消息', subtitle: '请填写表格，我们会尽快与您联系。', name: '姓名', email: '电子邮件', subject: '主题', message: '消息', submit: '发送消息', loading: '发送中...', success: '消息发送成功！感谢您的联系。', error: '发送消息时发生错误。请再试一次。' }, info: { title: '我们的信息', address: { title: '地址', value: 'Antônio Nápoli街229号<br/>圣保罗，SP, 02987-030, 巴西' }, phone: { title: '电话', value: '+55 (11) 5283-5040' }, email: { title: '电子邮件', value: 'contato@nowsolucoes.com.br' } } },
    solucoesPage: { hero: { title: '我们的解决方案', subtitle: '技术与创新，改变您公寓的安全与管理。' }, s1: { title: '门禁区域', description: '完整的出入控制解决方案，包括面部识别、二维码、数字邀请和与远程门房的集成，以实现最大的安全性和便利性。' }, s2: { title: '外部区域', description: '使用高清摄像头进行周边监控，带有人工智能的虚拟围栏，声光报警器和运动传感器，以全面保护公寓。' }, s3: { title: '内部区域', description: '对健身房、派对室和游泳池等公共区域的访问控制。确保只有授权的住户才能使用这些空间，并通过应用程序提供使用报告和预订功能。' }, s4: { title: '设施管理', description: '通过照明自动化系统、水泵控制和预防性维护管理来优化设施管理，降低成本并提高效率。' }, s5: { title: '定制解决方案', description: '我们理解每个公寓都是独一无二的。我们开发定制项目，整合不同技术，以满足您特定的安全和管理需求。' } },
    metadata: { home: { title: 'Now Soluções | 更多控制，更少成本', description: 'Now Soluções：智能公寓技术专家。我们提供门禁控制、人工智能监控、智能储物柜等。', keywords: '智能公寓, 公寓安全, 门禁控制, 远程门卫, now soluções' }, quemSomos: { title: '关于我们 | Now Soluções', description: '了解Now Soluções的历史和价值观，这家公司正以尖端技术和客户为中心，彻底改变公寓管理。', keywords: '关于now soluções, 历史, 价值观, 团队, 公寓管理' }, contato: { title: '联系我们 | Now Soluções', description: '与Now Soluções取得联系。提出问题、请求报价或与我们的安全与技术专家团队交谈。', keywords: '联系now soluções, 电话, 电子邮件, 地址, 公寓报价' }, solucoes: { title: '我们的解决方案 | Now Soluções', description: '了解Now为您的公寓提供的门禁区域、内外区域、设施和定制项目解决方案。', keywords: '公寓解决方案, 门禁区域, 人工智能监控, 设施, 定制项目' } },
    whatsappTooltip: '与专家交谈'
  }
};

export default translations;